### ISSUE TITLE
Maybe release binaries?

### ISSUE THREAD

**Issue by danwdart** [kjliew/qemu-3dfx#10]
Are you allowed to do that with watcom stuff? I forget.

**Comment by misutoneko** [comment]
IANAL but wouldn't that license only apply to OpenWatcom's source?
This project doesn't make any changes there.

However the kernel drivers are possibly a more problematic point. I'm not sure about their redistribution outside of the SDK.

**Comment by MirandaStreeter** [comment]
Is there a particular reason this was closed?

**Comment by danwdart** [comment]
Looks like it was because the README states that this is a paid service, afaik?
