### ISSUE TITLE
Error compiling on macOS Sonoma (re: SDL2)

### ISSUE THREAD

**Issue by sofakng** [kjliew/qemu-3dfx#105]
I've followed the instructions but about 30% through the compilation I have the following error:
`
FAILED: libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o 
cc -Ilibqemu-i386-softmmu.fa.p -I. -I../qemu-7.2.0 -I/opt/X11/include -Itarget/i386 -I../qemu-7.2.0/target/i386 -Iqapi -Itrace -Iui -Iui/shader -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/opt/homebrew/Cellar/glib/2.78.0/include -I/opt/homebrew/Cellar/glib/2.78.0/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.78.0/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.42/include -fcolor-diagnostics -Wall -Winvalid-pch -std=gnu11 -O2 -g -iquote . -iquote /Users/sofakng/Projects/qemu-3dfx/qemu-7.2.0 -iquote /Users/sofakng/Projects/qemu-3dfx/qemu-7.2.0/include -iquote /Users/sofakng/Projects/qemu-3dfx/qemu-7.2.0/tcg/aarch64 -DOS_OBJECT_USE_OBJC=0 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wno-initializer-overrides -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-string-plus-int -Wno-typedef-redefinition -Wno-tautological-type-limit-compare -Wno-psabi -Wno-gnu-variable-sized-type-not-at-end -fstack-protector-strong -DNEED_CPU_H '-DCONFIG_TARGET="i386-softmmu-config-target.h"' '-DCONFIG_DEVICES="i386-softmmu-config-devices.h"' -MD -MQ libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o -MF libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o.d -o libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o -c ../qemu-7.2.0/hw/mesa/mesagl_blit.c
In file included from ../qemu-7.2.0/hw/mesa/mesagl_blit.c:23:
In file included from ../qemu-7.2.0/hw/mesa/mesagl_impl.h:69:
../qemu-7.2.0/hw/mesa/mesagl_pfn.h:1:10: fatal error: 'SDL2/SDL_opengl.h' file not found
#include "SDL2/SDL_opengl.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
make: *** [run-ninja] Error 1
`

(Not sure why Github doesn't format that correctly...)

Homebrew is installed with sdl2, sdl2_gfx, and sdl2_image packages.  SDL_opengl.h exists in /opt/homebrew/include/SDL2/SDL_opengl.h and qemu configure was successful.

It seems like it's not including (-I) the /opt/homebrew/include path?

**Comment by kjliew** [comment]
A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation. You're free to make inquiry on the supported platform of choice prior to making a donation.
