### ISSUE TITLE
Compatibility with and Support for EmuGUI (Latest Stable or Dev Version) + One or more things before or other than that

### ISSUE THREAD

**Issue by feruenzerujkun** [kjliew/qemu-3dfx#107]
Does qemu-3dfx (latest version) via using QEMU v7.2.0 (or latest version = 8.1.0 or [other](https://qemu.weilnetz.de/w64/2023/)) be compatible (like also work on) with EmuGUI ([Stable](https://github.com/Tech-FZ/EmuGUI) or [Dev/PreRelease](https://github.com/Tech-FZ/EmuGUI-PreRelease) Versions) or is it possible to use without it?

e.g use cmd.exe (command prompt) or MingGW32 or MingGW64 (which ever I need to use for QEMU+3dfx), python (well the hard one), or other command-prompt alternatives

+ One or more things beforehand.
I would like some good-but-better enough directions on some installations for Windows XP vms for games that would not work on W10 and W11 (e.g Sacrifice, the one I couldn't get a chance to get it to work on QEMU or other) so I might be able to play it/them rather.

Here's some things + some lists that could help me or anyone (not always just me) deal with their problems with installing QEMU, the 3dfx files and others. Thanks in Advance!
1. Qemu-3dfx Installation Tutorial Video = Windows Version on YouTube
[![Watch the video](https://img.youtube.com/vi/U5UDzgg5cHw/maxresdefault.jpg)](https://youtu.be/U5UDzgg5cHw)

First Part (might have to suggest whpx other than haxm or other)
```
./qemu-img create f- qcow2 wxp.qcw 6G

./qemu-system-i386 -nodefaults -rtc base=localtime \
	-L ../qemu-8.1.0/pc-bios \
	-M pc,accel=whpx,kernel-irqchip=off -m 512 -display sdl \
	-device VGA -device virtio-blk-pci,drive=boot0 -device lsi -device ac97 \
	-netdev user,id=net0 -device virtio-net-pci,rombar=0,netdev=net0 \
	-drive if=floppy,file=virtio_vfd.qcw \
	-drive id=boot0,if=none,file=wxp.qcw \
	-device scsi-cd,drive=xpcd -drive id=xpcd,if=none,media=cdrom,file=winxp.iso \
	-boot d
```

Second Part
```
./qemu-system-i386 -nodefaults -rtc base=localtime \
	-L ../qemu-8.1.0/pc-bios \
	-M pc,accel=whpx,kernel-irqchip=off -m 512 -display sdl \
	-device VGA -device virtio-blk-pci,drive=boot0 -device lsi -device ac97 \
	-netdev user,id=net0 -device virtio-net-pci,rombar=0,netdev=net0 \
	-drive if=floppy,file=virtio_vfd.qcw \
	-drive id=boot0,if=none,file=wxp.qcw \
	-device scsi-hd,drive=demo -drive id=demo,if=none,snapshot=on,file=fat:ro:_demo_ \
	-device scsi-cd,drive=vmad -drive id=vmad,if=none,media=cdrom,file=vmaddons.iso
```

What do I need(A):
FILES:
virtio_vfd.qcw = virtio-win-0.1.141_x86.vfd (can be converted to qcw/QCOW2
winxp.iso = Windows XP Service Pack 3 (must be mounted on Virtual CDrom Drive)
vmaddons.iso = VMAddons

DRIVERS(A):
Advanced Configuration and Power Interface (ACPI) PC
Red Hat VirtIO BLOCK Disk Device WinXP/32-bit
Red Hat VirtIO Ethernet Adapter
QEMU Bochs SVGA or QEMU Bochs SVGA PCI
SigmaTel C-Major Audio
Red Hat VirtIO SCSI controller

ANYTHING?(A):
Wine3D (mentioned in the readme page of qemu-3dfx)

VMAddons (mentioned in the video)
wine-get ddthru
3DMark06
wine-get ddthru undo
wine-get ddthru
wine-get re4gen init
wine-get install ?
wine-get install 7.0.1 ?
wine-get install 7.0.1 d3d9 /c/Futuremark/3DMark06/
wine-get glInfo

2. QEMU Sacrifice (2000) - the one game I couldn't get to work on Windows10 with or without the XP-VM
[![Watch the video](https://img.youtube.com/vi/BOmpPp6IKzE/maxresdefault.jpg)](https://youtu.be/BOmpPp6IKzE)

What do I (do, but) need(B):
UltraEdit32 (OPTIONAL)
MINGW32 (used in the video)
cd /d/Shiny/Sacrifice
wine-get version
cat wine.reg
DirectDraw HAL
Wine D3D7 T&L HAL
Creative Labs EAX 2 (TM) (used in the video)
Shiny Direct3D wrapper
ATI Raedon 9500 (used in the video)
Driver Version 6.14.10.6764 (67.64)
wine-get glinfo

**Comment by kjliew** [comment]
I don't use any GUI frontend for QEMU. If you wished to have one, then the question of compatibility belongs to the project/author who develop such GUI frontend, not here. For command prompt alternatives, well, if you had built QEMU from source, then that wouldn't have been a question at all.

>What do I need(A)
What do I (do, but) need(B):

The many episodes of **"From Install to Play in 15 mins"** videos on YouTube tell the clues on getting games to play on QEMU virtual machines. For those who still can't grasp the ideas of virtual machines, I believe having the games from GOG/Steam would have been a better option. **QEMU general usability issues are out of scope of this project.** Google is your BEST friend.

You can also made a small donation to support the Project and Game Preservation. QEMU prebuilt binary package will be delivered for you. You will then have the option of exercising Game Election to make any games work for you on QEMU. Details at https://github.com/kjliew/qemu-3dfx#donation.
