### ISSUE TITLE
Guest Wrapper build error in WSL2

### ISSUE THREAD

**Issue by l-zhang-1983** [kjliew/qemu-3dfx#108]
![image](https://github.com/kjliew/qemu-3dfx/assets/7477805/d7e9125c-16f8-4536-8a5a-7fab0de4fbde)

@kjliew Thank you for your rapid reply and modification of the code for Guest Wrapper syntax error.

However, after pulling the new code, another error occurred as shown above.

My specs: Windows 11 Pro 23H2, WSL2 - Ubuntu 22.04.3 LTS

QEMU-7.2.6

**Comment by kjliew** [comment]
That's the problem with Ubuntu/Debian or any Linux distros that symlink `/bin/sh` to `dash`. You can either:
1. Restore symlink `/bin/sh` to `bash`.
2. Force bash for makefile `$ make SHELL=/bin/bash`

**Comment by l-zhang-1983** [comment]
![image](https://github.com/kjliew/qemu-3dfx/assets/7477805/dde30860-f704-4b2b-a70e-3bab11a1c17e)

Works like a charm! THANK YOU @kjliew
