### ISSUE TITLE
Hi do you want and can you make old real pc bios functional in qemu?

### ISSUE THREAD

**Issue by Raduq91** [kjliew/qemu-3dfx#111]
Hi do you want and can you make old real pc bios functional in qemu?
Long time ago when I tried PCem, 86box, etc, I liked that it had working real bios.
There are a few old real pc bios files that qemu can boot, there are a few visual glitches at startup and I can modify bios settings but when exiting bios setup, qemu freezes.
659_10.bin
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/f0d25c74-5df3-49d2-83cd-b7493af77fd5)
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/0627797f-9f4f-441c-bb10-9072b94d6308)
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/9adda98a-3b85-4dea-8895-a0ce8b6ad1a7)

Dif version, SBC-659_19.bin:
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/db4963a3-3710-4508-be0b-bdaac19f91c6)
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/246595e2-7d24-4d44-ac07-1fe16429c40b)

Dif bios, acorp_awd_600pgn_i815.BIN:
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/2f9106dc-c529-4721-afe1-d48265f6fa72)
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/ef9cf3aa-1721-420f-a358-66721243eef8)
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/7c5895ce-a0fd-47f7-8ff3-efb0c03f40f9)
![image](https://github.com/kjliew/qemu-3dfx/assets/31180871/f7ad890b-c1d7-4b44-a612-937ddfa8f427)

qemu-system-x86_64 -bios SBC-659_19.BIN -cpu 486 -machine pc -m 256  -drive file=c.img -boot c

config.sys: himemx.exe /max=64m

**Comment by kjliew** [comment]
No, thanks. Such **\*USELESS\* and waste-of-time** endeavor shall be left for whatever "Trash"Boxes or "脑残のPC"em-U-lation. The focus of this project is **Games Preservation**.
