### ISSUE TITLE
Would like to support but donations not available

### ISSUE THREAD

**Issue by sakamoto-neko** [kjliew/qemu-3dfx#113]
I was trying to use the donate button but this appeared
![Capture](https://github.com/kjliew/qemu-3dfx/assets/17673235/6af8b70e-7ce9-497c-8bf9-fa8c70c2251e)

Do let me know of an alternative way (I think transfer via Paypal should be possible).

**Comment by kjliew** [comment]
I added GitHub Sponsor link for transfer via Paypal. Hope this works for you.

BTW, which countries are prohibited by Paypal for initiating donations? It's good for me to be aware of such limitation. Thanks.

**Comment by sakamoto-neko** [comment]
I'm donating from Singapore, not sure why mine was restricted.

After I send donation, should I communicate through your email?

**Comment by kjliew** [comment]
You're free to use any form of communication. GitHub or email is fine.

**Comment by sakamoto-neko** [comment]
Email sent, thanks.

**Comment by kjliew** [comment]
Thank YOU for supporting the Project and Games Preservation. I confirmed receipt of your donation through Paypal.
