### ISSUE TITLE
Does QEMU-3DFX support SDLGL on macOS or does it require X11 (Xquartz) ?

### ISSUE THREAD

**Issue by sofakng** [kjliew/qemu-3dfx#117]
I'm looking through the patches and it looks like you have a file (mglcntx_sdlgl.c) that is not included in compilation.

Is this on purpose?

The result is that macOS requires Xquartz (X11) support but this is further confusing because I don't see Xquartz opening during your YouTube videos.

**Comment by kjliew** [comment]
Bingo👍! You've completed the quest 🏆in search of the Holy Grail🤣!!

You're free to submit a PR to help me resolve this or fork this project, maintain it and offer builds & support for the Mac community. Isn't FOSS such a wonderful journey😜?

Thank you for watching and paying attentions to qemu-3dfx YouTube videos. It is definitely rewarding for deciphering the codes embedded within those videos, isn't it?

**Comment by sofakng** [comment]
I'm not sure how to interpret what you're saying...

Are you saying that the macOS portion of this code needs fixing?

**Comment by kjliew** [comment]
It really depends on whom you're talking to.

A PR is always welcome. Otherwise, it "works" for me...🤣

**Comment by sofakng** [comment]
Are you using the same patches and code available on this GitHub or are there additional patches that you haven't uploaded?
