### ISSUE TITLE
Failure when compiling on msys2 with error : ERROR: "Unknown variable "targetos".

### ISSUE THREAD

**Issue by sdkmap** [kjliew/qemu-3dfx#120]
Hey there! 🚀 I attempted compiling your project on MSYS2, but it's throwing an error after command  `../configure --target-list=i386-softmmu --enable-whpx --enable-sdl --disable-capstone --enable-fdt=system` with the error being `**"ERROR: Unknown variable  'targetos'. ERROR: meson setup failed**`
" 😕 I made sure to patch the files and install the necessary packages, but the issue persists. I'd love to donate to the project, but unfortunately, the recent price increase from $60 to $90 is beyond my budget at the moment. Any assistance to resolve this issue would be greatly appreciated!

**Comment by sdkmap** [comment]
after deleting the the part that causes this error I've managed to get it the configure part working but now this error pops up when launching make :
```
 ../hw/mesa/mesagl_blit.c:89:9: error: ISO C90 forbids variable length array 'srcbuf' [-Werror=vla]
   89 |         char srcbuf[srclen];
      |         ^~~~
cc1.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make: *** [Makefile:162: run-ninja] Error 1

```

**Comment by kjliew** [comment]
>... the recent price increase from $60 to $90 is beyond my budget at the moment ...

The bump, though regrettable, is inevitable. Why have you waited til then?!😜 That's the explicit cost to pay for wait-and-see stance.🤣 The bump helps other projects look more competitive on "price", stimulates competitions and values appreciation for Game Preservation. You're welcome to look for other "FREE" as of free-beer alternatives.

A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation. You're free to make inquiry on the supported platform of choice prior to making a donation.

**Comment by sdkmap** [comment]
nah mate i've managed to compile just needed to use the gnu99 mode, you can close the issue if you want to
