### ISSUE TITLE
./hw/meson.build:1:8: ERROR: Unknown variable "i386_ss"

### ISSUE THREAD

**Issue by tomnic79** [kjliew/qemu-3dfx#121]
[meson-log.txt](https://github.com/kjliew/qemu-3dfx/files/14474508/meson-log.txt)
Hi Kjliew, I've tried to compile the latest version of qemu-3dfx following your guide but I get this error:

Executing subproject keycodemapdb 

keycodemapdb| Project name: keycodemapdb
keycodemapdb| Project version: undefined
keycodemapdb| Program tools/keymap-gen found: YES (/home/tomnic/myqemu/qemu-3dfx/qemu-8.2.1/subprojects/keycodemapdb/tools/keymap-gen)
keycodemapdb| Build targets in project: 275
keycodemapdb| Subproject keycodemapdb finished.

../hw/meson.build:1:8: ERROR: Unknown variable "i386_ss".

A full log can be found at /home/tomnic/myqemu/qemu-3dfx/qemu-8.2.1/build/meson-logs/meson-log.txt

ERROR: meson setup failed

I'm using PopOS 22.04 LTS as OS. Can you suggest me please a way to solve this issue? I'd like to try this latest version with KVM acceleration, way far better than WHPX

**Comment by kjliew** [comment]
I suggest that you wipe `myqemu` and start all over from scratch. It seemed that you didn't follow the build steps precisely, especially `$ bash ../scripts/sign_commit`. It is not possible to get meson to fail with that error.

**Comment by tomnic79** [comment]
Thanks it's working... I didn't notice some errors applying bash ../scripts/sign_commit command, thanks a lot!
