### ISSUE TITLE
Guest Wrap build result less than expected

### ISSUE THREAD

**Issue by l-zhang-1983** [kjliew/qemu-3dfx#122]
I fellowed the instruction to build the Guest Wrap, and got the result shown in this screenshot

![image](https://github.com/kjliew/qemu-3dfx/assets/7477805/47a0e6ba-e685-4599-9478-bee8da53dbba)

The target is 7 files

1. fxmemmap.vxd
2. glide.dll
3. glide2x.dll
4. glide3x.dll
5. **MISSING ONE**
6. opengl32.dll
7. fxptl.sys
8. instdrv.exe

However, in the Installing section of README.md, there should be 8 files to use, and the MISSING ONE is "glide2x.ovl"

![Screenshot 2024-03-05 105028](https://github.com/kjliew/qemu-3dfx/assets/7477805/e04da889-125a-40ef-8f72-98c87196ab95)

I wonder what I have missed in building and compiling, or something wrong in configuration or dependency?

How to make the missing glide2x.ovl come out?

**Comment by hughobrien** [comment]
I suggest checking if you have Watcom available

**Comment by kjliew** [comment]
@hughobrien Thank you. 👍 

And `'i[56]86-pc-msdosdjgpp'` toolchain for DJGPP DXE wrappers.
DXE/OVL wrappers, though available, aren't very interesting on QEMU. Use DOSBox for DOS games.
