### ISSUE TITLE
closed source app rendering to open source app window

### ISSUE THREAD

**Issue by roberttryton** [kjliew/qemu-3dfx#124]
an issue arose on vogons with rendition verite wrapper which also applies to this project,
that a closed source app cannot legally render to an open source app window.
https://www.vogons.org/viewtopic.php?p=1249400#p1249400

**Comment by kjliew** [comment]
As usual, the Unprofessional VOGONS Moderator @vogonsorg purged the thread upon his own conspiracy delusions.
