### ISSUE TITLE
Softgpu and qemu 3dfx

### ISSUE THREAD

**Issue by neofeo** [kjliew/qemu-3dfx#131]
Hi buddy, Salvadoe from microlinux. Last days I were testing wibdows 98 on quemu3dfx with softemu. Let say that I wanted the native opengl passthrough of your project alongisde wine d3d. It seems that you part works fine when running Claw (1997). I can see mesa on the qemu output. The framerate isn't that great, I am on J4125 with kvm enabled of course. I wonder if it's  expected to not work perfectly or maybe the softgpu side is int doing what I ask, to use that native gl to trabslate dx to opengl properly. 

Also, I've tested qemu3dfx directly to sdl2 kmsdrm and works, that being said, I have some problems with mouse detecting the display size. Probably something that could be resolved witha  more up to date sdl2 since I am on jammy sdl2. The idea behind qemu-3dfx running  on sdl2 kmsdrm is to be able to run qemu-3dfx out of the box at linux boot without any desktop at all.

I would  like to at least showcase it. So, if you can give me some hints or if we could have some feedback from discord, send me a PM at https://discord.com/invite/UG2RXRdpHs

**Comment by kjliew** [comment]
Claw (1997) works without any Wine DLLs. It does not make use of Direct3D so the OS `ddraw.dll` and vmdisp9x/boxv9x just work and simpler. The game seems to lock at 30 FPS.

SDL2 kmsdrm wasn't very stable last time I checked. The kernel panicked on it while no problem within X or Wayland compositors. It is probably not a popular use case that could win the attentions from upstream development.

**Comment by neofeo** [comment]
If so, why mesa show up on the qemu console? That wouldn't make sense if there is no call to opengl and wined3d. I placed opebgl32.dll too.

**Comment by kjliew** [comment]
I meant to say Wine DLLs are **_OPTIONAL_**. If you wanted to have the game run with it, then it works, too. It is just redundant for any DirectX games that don't need Direct3D or DirectDraw HAL caps. Any standard 2D display-only support always exposes DirectDraw HEL and have CPU do the jobs.

**Comment by neofeo** [comment]
Ahh gotcha, thanks KJ, have a nice day. Amazing work.
