### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by ICrashWindows12** [kjliew/qemu-3dfx#132]
Cleaning... 0 files.
Running postconf script '/Users/red/Desktop/qemu-3dfx/build/pyvenv/bin/python3.12 /Users/red/Desktop/qemu-3dfx/qemu-8.2.1/scripts/symlink-install-tree.py'
/Users/red/Desktop/qemu-3dfx/build/pyvenv/bin/meson introspect --targets --tests --benchmarks | /Users/red/Desktop/qemu-3dfx/build/pyvenv/bin/python3.12 -B scripts/mtest2make.py > Makefile.mtest
[1/3663] Generating qemu-version.h with a custom command (wrapped by meson to capture output)
[2/3659] Generating tests/include/QAPI test (include) with a custom command
[3/3659] Compiling C object libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o
FAILED: libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o 
cc -Ilibqemu-i386-softmmu.fa.p -I. -I../qemu-8.2.1 -I/opt/X11/include -Itarget/i386 -I../qemu-8.2.1/target/i386 -Iqapi -Itrace -Iui -Iui/shader -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/usr/local/Cellar/capstone/4.0.2/include/capstone -I/opt/homebrew/Cellar/glib/2.80.0_2/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.80.0_2/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.43/include -I/opt/homebrew/Cellar/glib/2.80.0_2/include -fcolor-diagnostics -Wall -Winvalid-pch -std=gnu11 -O2 -g -fstack-protector-strong -Wundef -Wwrite-strings -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wmissing-format-attribute -Wno-initializer-overrides -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-string-plus-int -Wno-typedef-redefinition -Wno-tautological-type-limit-compare -Wno-psabi -Wno-gnu-variable-sized-type-not-at-end -iquote . -iquote /Users/red/Desktop/qemu-3dfx/qemu-8.2.1 -iquote /Users/red/Desktop/qemu-3dfx/qemu-8.2.1/include -iquote /Users/red/Desktop/qemu-3dfx/qemu-8.2.1/host/include/aarch64 -iquote /Users/red/Desktop/qemu-3dfx/qemu-8.2.1/host/include/generic -iquote /Users/red/Desktop/qemu-3dfx/qemu-8.2.1/tcg/aarch64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -fno-pie -DNEED_CPU_H '-DCONFIG_TARGET="i386-softmmu-config-target.h"' '-DCONFIG_DEVICES="i386-softmmu-config-devices.h"' -MD -MQ libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o -MF libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o.d -o libqemu-i386-softmmu.fa.p/hw_mesa_mesagl_blit.c.o -c ../qemu-8.2.1/hw/mesa/mesagl_blit.c
In file included from ../qemu-8.2.1/hw/mesa/mesagl_blit.c:23:
In file included from ../qemu-8.2.1/hw/mesa/mesagl_impl.h:72:
../qemu-8.2.1/hw/mesa/mesagl_pfn.h:1:10: fatal error: 'GL/glcorearb.h' file not found
#include <GL/glcorearb.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
make: *** [run-ninja] Error 1

**Comment by kjliew** [comment]
A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation.

**Comment by ICrashWindows12** [comment]
I cannot buy that, and also because I am buying a PC right now, going from mac to PC. So, help me solve it
