### ISSUE TITLE
cannot compile. 

### ISSUE THREAD

**Issue by ICrashWindows12** [kjliew/qemu-3dfx#134]
![Screenshot 2024-06-07 at 16 53 59](https://github.com/kjliew/qemu-3dfx/assets/73936448/77bec244-677a-4dc6-8089-29a25cbd5482)
I am also not donating since it is not necessary for the pre-made files. I want to fix any problems. 1 Error is with the file glcorearb.h which is necessary. Yes I have installed xquartz and xquartz works, but the file may be broken or some error in the code means i have to install another library or like try to get the file working

**Comment by ICrashWindows12** [comment]
note: I am not paying to for a pre-made, I only got up to like compiled 5000 or something, it did not make it all the way.

**Comment by kjliew** [comment]
A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation.

**Comment by fuel-pcbox** [comment]
@ICrashWindows12 Hey, if you want a PC emulator that's NOT developed by a raging narcissist, you should try out 86Box at [86box.net](86box.net). It also has FREE premade binaries for Windows, macOS, and Linux!

NOTE: I'm not affiliated with the 86Box project, I just think it's better than the shit this loser is peddling.
