### ISSUE TITLE
Windows xp 64 bits please

### ISSUE THREAD

**Issue by Raspberrygamer** [kjliew/qemu-3dfx#136]
After months of trying I managed to get qemu3dfx to work. The reason I couldn't get it before was the Windows XP version. I always use Windows XP 64bits as my main vm because it's very fast. So I tested Windows XP sp3 and it worked right away. So would you have a patch for me to apply to my Windows XP 64bits? I've tried everything, even moved fxpl.sys to the syswow drivers folder and it didn't work either.

**Comment by kjliew** [comment]
No, just use 32-bit Windows XP.

**Comment by fuel-pcbox** [comment]
Hey, if you want a PC emulator that's NOT developed by a raging narcissist, you should try out 86Box at [86box.net](86box.net). It also has FREE premade binaries for Windows, macOS, and Linux!

NOTE: I'm not affiliated with the 86Box project, I just think it's better than the shit this loser is peddling.
