### ISSUE TITLE
Building Wrappers Issue

### ISSUE THREAD

**Issue by MarioNooo** [kjliew/qemu-3dfx#139]
Ok so I discovered this project on Google by searching "Windows XP 3d accelerated VM". I managed to just compile the qemu binary but I have problems with building the wrappers as I get this error
```
 make: *** No rule to make target 'fxhook.o', needed by 'glide.dll'.  Stop.
make: *** Waiting for unfinished jobs....
  CC  fxhook.o fxhpat.o fxlib9x.o fxlibnt.o fxtime.o md5.o 
```
My host OS is Arch Linux

**Comment by kjliew** [comment]
A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation.

**Comment by MarioNooo** [comment]
Couldn't you at least give me some advice instead of "nah, you should give me a 'small' donation $90 dollars so you don't have to compile it manually"?

**Comment by Dungeonseeker** [comment]
@MarioNooo 
Wrappers only

1) Install `aur/djgpp-djcrx-bootstrap` < THIS HAS TO BE INSTALLED FIRST!!
2) install `aur/djgpp-djcrx` (it will pull everything else as dependency)
3) Hope it builds, if it doesn't then you have to go to `$HOME/cache/yay/djgpp-djcrx` and build manually using `makepkg -si`
4) Run `sudo ln -sf /bin/i686-pc-msdosdjgpp-dxe3gen /bin/dxe3g`
5) Install `mingw-w64-*` (they're all in the extra repo)
6) Install `aur/mingw-w64-tools`
7) Install `aur/openwatcom-v2`
8) Run source `/opt/watcom/owsetenv.sh`
9) Follow the guide for build wrappers
10) Profit

**Comment by MarioNooo** [comment]
Wow, you were really helpful but I actually gave up doing this! Sorry bro!

**Comment by fuel-pcbox** [comment]
@MarioNooo Hey, if you want a PC emulator that's NOT developed by a raging narcissist, you should try out 86Box at [86box.net](86box.net). It also has FREE premade binaries for Windows, macOS, and Linux!

NOTE: I'm not affiliated with the 86Box project, I just think it's better than the shit this loser is peddling.

**Comment by kjliew** [comment]
@fuel-pcbox Oh, you forgot the cause why the OP visited here. Allow me to remind you of it, it was "Windows XP 3D accelerated VM". Are you gonna **_\*bluff through the roof\*_** once more by telling "86Box is good enough for Windows XP"?

@Dungeonseeker Hey bro, how's your progress? Perhaps you can also show your trophy to wake our friend @fuel-pcbox up from the dreams and hallucination in **_Accuracy \*BS\*_**.

**Comment by MarioNooo** [comment]
I don't want an emulator or a "3D accelerated VM". I can just run old games on Wine and hope it'll work. Just look at those 3DMark03 benchmark scores 
![Screenshot_20240908_185312](https://github.com/user-attachments/assets/f13481f2-61da-4e33-ae82-a046edaf4134)

**Comment by Mungr3ss** [comment]
> @MarioNooo Wrappers only
> 
> 1. Install `aur/djgpp-djcrx-bootstrap` < THIS HAS TO BE INSTALLED FIRST!!
> 2. install `aur/djgpp-djcrx` (it will pull everything else as dependency)
> 3. Hope it builds, if it doesn't then you have to go to `$HOME/.cache/yay/djgpp-djcrx` and build manually using `makepkg -si`
> 4. Run `sudo ln -sf /bin/i686-pc-msdosdjgpp-dxe3gen /bin/dxe3gen`
> 5. Install `mingw-w64-*` (they're all in the extra repo)
> 6. Install `aur/mingw-w64-tools`
> 7. Install `aur/openwatcom-v2`
> 8. Run `source /opt/watcom/owsetenv.sh`
> 9. Follow the guide for build wrappers
> 10. Profit

is djgpp supposed to take ages to build? keeps failing. anyone got a pre-built i686-pc-msdosdjgpp pkg they can share?
