### ISSUE TITLE
sign_commit can't find vl.c

### ISSUE THREAD

**Issue by misutoneko** [kjliew/qemu-3dfx#14]
Looks like the += notation used in the sign_commit script is not understood by the default /bin/sh in Linux.
It gives an error message and if compilation is attempted, it will eventually fail at vl.c with "undefined reference to `ALIGNED'".

I replaced line 10 with:
SRC=$SRC" "$(find -maxdepth 2 -name vl.c)

that seems to work (only tested on Linux).

**Comment by kjliew** [comment]
I can't reproduce the issue on ArchLinux and this is my `sh --version`. It is just a symlink to bash.
```
$ uname -a
Linux 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux

$ sh --version
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Which flavors and version of of Linux? Can you provide `uname -a` and `sh --version`?

**Comment by misutoneko** [comment]
Oh wow I see it now...this is on Linux Mint 20, they're using **dash** as the default shell.
I wonder what was the rationale behind that.

Btw "sh --version" bombs an error message:
sh: 0: Illegal option --

**Comment by kjliew** [comment]
Just use **bash**.
