### ISSUE TITLE
Basic support of android es api

### ISSUE THREAD

**Issue by Mateus2022** [kjliew/qemu-3dfx#143]
somehow everything depends on x server (or something like that) android uses a type of ANativewindow/Surface flinger and AHB, passing the egl/gles api to a mesapt and within windows it requires a lot of api compatibility that android almost doesn't even support properly For these types of processes, something relevant would be to pass the API over a "wrapper" layer that recreates the entire X protocol and creates extra contexts to have basic support for 3dfx,

a and about how I am able to use qemu-3dfx on android the reason would be because of termux which emulates a usr prefix which enables a container on android in bionic c which has apt and other things (it can use android libraries)

extra details is that there is virglrenderer-android the problem is that it is so messed up (wrapper) that 3d acceleration is slow and it also only works in the proot container without being in the termux itself (virglrenderer-android uses api gles and simulates a tmp being usable in proot) another that termux has packages that are from the mesa and has llvm drivers etc. which also interferes,

Thanks!!.

**Comment by kjliew** [comment]
Upstream QEMU only supports Windows, Linux and macOS builds.
