### ISSUE TITLE
Nightmare Creatures GetVid bug

### ISSUE THREAD

**Issue by xoureldeen** [kjliew/qemu-3dfx#146]
Os:
Windows XP Professional x64

Host:
poco x4 5g pro
snapdragon 695
adreno 619

Qemu Parameters:
`-device ac97 -usb -cpu qemu64,+avx,+avx2,+3dnow,+3dnowext,+3dnowprefetch -smp 4 -m 512 -vga vmware  -device rtl8139,netdev=n0 -netdev user,id=n0 -accel tcg,thread=multi,tb-size=2048 -boot d,menu=on  -rtc base=localtime -accel tcg,thread=multi -display gtk,gl=on`

Screenshots:
![Screenshot_2024-12-28-21-59-02-701_com vectras vm](https://github.com/user-attachments/assets/a45d48a2-6f28-4b92-9a6a-af1a8964878b)
![Screenshot_2024-12-28-21-59-44-142_com vectras vm](https://github.com/user-attachments/assets/03564bb1-b320-424e-9c57-b5b0b1ed28a7)

wrappers are installed correctly and opengl.dll exist in game folder, qemu 8.2.1 3dfx patched

**Comment by kjliew** [comment]
Get a cheap PC or laptop and donate to support Game Preservation.

**Comment by xoureldeen** [comment]
> احصل على جهاز كمبيوتر شخصي أو كمبيوتر محمول رخيص وقم بالتبرع به لدعم الحفاظ على اللعبة.

what??, i just wanted to add 3dfx support into my app, for sure i have 3 high end PC's, bro im just ask why 3dfx not work because i seen on youtube u ran this games.
