### ISSUE TITLE
How to run older openGL games in win9x?

### ISSUE THREAD

**Issue by RobertSpir** [kjliew/qemu-3dfx#15]
I'm trying to run quake 2 demo with opengl, but it fails on SetPixelFormat, qemu log is
```
mesapt: DLL loaded
glcntx: ChoosePixelFormat() fmt 0x0c
glcntx: PixFmt 0x0c nAux 4 nSamples 0 0
glcntx: SetPixelFormat() fmt 0x0c ret 0
glcntx: ChoosePixelFormat() fmt 0x0c
glcntx: PixFmt 0x0c nAux 4 nSamples 0 0
glcntx: SetPixelFormat() fmt 0x0c ret 0
mesapt: DLL unloaded
```

**Comment by kjliew** [comment]
Legacy OpenGL games require GL extensions limit. It is recommended to limit GL extensions to the year or year+1 of the game when it was released. There are 2 ways to do this.

1. **Host side GL extensions limit**
Create a file named `mesagl.cfg` in the same path as `qemu-system-i386`. GL extensions will be limited to the specific year for **all OpenGL games** in the Guest OS.
```
$ echo "ExtensionsYear,1998" >mesagl.cfg
```
2. **Guest side GL extensions limit**
Create a file named `wrapgl32.ext` in the same path as `opengl32.dll` guest wrapper which was placed into the `Game Installed` location. GL extensions will be limited to the specific year on **per-game basis**. Additional GL extensions can be **excluded** by appending the extensions name strings. This is supported after commit a08d0d4d6a99c45079b15fc6dd7eafb64f6cf813
```
D:\Games\Quake2> echo ExtensionsYear,1998 >wrapgl32.ext
D:\Games\Quake2> echo GL_EXT_point_parameters >>wrapgl32.ext
D:\Games\Quake2> echo GL_EXT_compiled_vertex_array >>wrapgl32.ext
```

**Comment by RobertSpir** [comment]
doesn't work, host side or guest side, still the same problem

**Comment by kjliew** [comment]
Then please provide more details on both host and guest configuration. I downloaded Quake 2 demo and it worked. Your log showed that SetPixelFormat() had failed. Do you have functional OpenGL on the host? What's your host GPU?
```
mesapt: DLL loaded
glcntx: ChoosePixelFormat() fmt 0x0b
glcntx: PixFmt 0x0b nAux 4 nSamples 0 0
glcntx: SetPixelFormat() fmt 0x0b ret 1
glcntx: DescribePixelFormat() dwFlags:00008025
  cColorbits:32 cDepthBits:24 cStencilBits:08 ARGB8888
  cAlphaShift:24 cRedShift:16 cGreenShift:08 cBlueShift:00
mesapt: wglCreateContext cntx 0 curr 0
mesapt: wglMakeCurrent cntx 1 curr 0 lvl 0
mesapt: 6833fdf-22:08:34 Apr 17 2021 build WRAPGL32
mesapt: VertexArrayCache 32MB
mesapt: DispTimerSched 2000ms
mesapt: MappedBufferObject Zero-copy
mesapt: Guest GL Extensions pass-through for Year ALL Length ANY
mesapt: ATI Technologies Inc. [ 22 ]
mesapt: AMD Radeon(TM) Vega 8 Graphics [ 31 ]
mesapt: 4.6.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6 [ 65 ]
mesapt: Guest GL Extensions limit to Year 1998
glcntx: wglSwapIntervalEXT(1) ret 1
mesapt: wglDeleteContext cntx 1 curr 1 lvl 0
mesapt: VertexArrayStats: elemMax 000000 vertexCache 0000
mesapt: MGLStats: fifo 0x0016324 data 0x000b0f0
mesapt: DLL unloaded
```

**Comment by RobertSpir** [comment]
Host gpu is nvidia RTX 3080, opengl works without problems (At least all the demos in gpu caps viewer), the same problem is even if I try to use opengl32.dll from mesa with software rendering (by putting it to the folder with qemu binary)

guest is windows ME installed as described in https://github.com/kjliew/qemu-3dfx/wiki, I don't think that there are some critical differences between windows ME and 98 SE that should cause this problem.

Qemu and opengl guest wrapper are built using latest msys2.

**Comment by RobertSpir** [comment]
![winme](https://user-images.githubusercontent.com/17044552/116650454-6a0c5300-a981-11eb-89f8-f8632708cb5f.jpg)

**Comment by kjliew** [comment]
I see. You didn't have `-display sdl` when starting QEMU. If QEMU is built with GTK libs, then you need that. Otherwise, QEMU will use GTK display by default. Unfortunately, QEMU GTK display currently does not have the required UI plumbing for MESA GL/3Dfx Glide pass-through to work with it. This seems to be a popular misstep for new comers.

Usually, MSYS2/mingw-w64 native apps in Windows 10 are rarely built with GTK libs but they are available anyway. You can remove them and re-configure QEMU with only SDL2. `$ pacman -Rusc mingw-w64-x86_64-{gtk2,gtk3,gtk4}`

**Comment by RobertSpir** [comment]
thanks, works now
