### ISSUE TITLE
Can't compile wrappers on MSYS2 / Windows 10

### ISSUE THREAD

**Issue by mr-falafel** [kjliew/qemu-3dfx#17]
Followed the instructions in the readme and got the result below. I'm using the same installation I used to compile the main qemu binaries, which is to say a fresh MSYS2 installation with base-devel and mingw-w64-x86_64-{toolchain,binutils,gcc,pixman,SDL2,glib2,meson}, plus mingw-w64-i686-toolchain. I strongly suspect the problem might be due to missing pexports, since that's listed as a build dependency. Except that pexports is apparently not part of MSYS2 so I don't know how to solve that problem. I'm more than happy to cross-build on linux or setup another mingw environment, if someone can guide me through their process.

edit: I figured I should make this separate from the other build issue, since it doesn't relate to the core binaries, but feel free to correct me. :)

Result of make && make clean:
`make && make clean
  CC  fxhook.o fxlib9x.o fxlibnt.o
../../fxlib/fxhook.c: In function 'HookParseRange':
../../fxlib/fxhook.c:104:30: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  104 |     if (addr && (0x4550U == *(uint32_t *)addr)) {
      |                              ^
../../fxlib/fxhook.c:106:25: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  106 |             if (!memcmp((void *)(addr + i), idata, sizeof(idata))) {
      |                         ^
../../fxlib/fxhook.c:107:26: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  107 |                 addr += ((uint32_t *)(addr + i))[3];
      |                          ^
../../fxlib/fxhook.c:108:24: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  108 |                 *iat = (uint32_t *)addr;
      |                        ^
../../fxlib/fxhook.c:114:25: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  114 |             if (addr == (uint32_t)(*iat))
      |                         ^
../../fxlib/fxhook.c:116:25: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  116 |             if (!memcmp((void *)(addr + i), rdata, sizeof(rdata))) {
      |                         ^
../../fxlib/fxhook.c:117:26: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  117 |                 addr += ((uint32_t *)(addr + i))[3];
      |                          ^
../../fxlib/fxhook.c:118:24: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  118 |                 *iat = (uint32_t *)addr;
      |                        ^
../../fxlib/fxhook.c: In function 'HookPatchTimer':
../../fxlib/fxhook.c:133:18: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  133 |     if ((addr == (uint32_t)patch) &&
      |                  ^
../../fxlib/fxhook.c:135:24: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  135 |         DWORD hkTime = (DWORD)GetProcAddress(GetModuleHandle("winmm.dll"), "timeGetTime"),
      |                        ^
../../fxlib/fxhook.c:137:15: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  137 |               (DWORD)GetProcAddress(GetModuleHandle("kernel32.dll"), "QueryPerformanceCounter"):0;
      |               ^
../../fxlib/fxhook.c:143:28: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  143 |                 patch[i] = (uint32_t)&TimeHookProc;
      |                            ^
../../fxlib/fxhook.c:148:28: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  148 |                 patch[i] = (uint32_t)&elapsedTickProc;
      |                            ^
../../fxlib/fxhook.c: In function 'HookTimeGetTime':
../../fxlib/fxhook.c:166:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  166 |         uint16_t *callOp = (uint16_t *)(caddr - 0x06);
      |                            ^
../../fxlib/fxhook.c:168:21: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  168 |             addr = *(uint32_t *)(caddr - 0x04);
      |                     ^
../../fxlib/fxhook.c:170:21: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  170 |             patch = (uint32_t *)addr;
      |                     ^
../../fxlib/fxhook.c:175:12: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  175 |     addr = (uint32_t)GetModuleHandle(mod); \
      |            ^
../../fxlib/fxhook.c:183:5: note: in expansion of macro 'TICK_HOOK'
  183 |     TICK_HOOK(0);
      |     ^~~~~~~~~
../../fxlib/fxhook.c:177:25: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  177 |         if (0x4550U == *(uint32_t *)addr) break; \
      |                         ^
../../fxlib/fxhook.c:183:5: note: in expansion of macro 'TICK_HOOK'
  183 |     TICK_HOOK(0);
      |     ^~~~~~~~~
../../fxlib/fxhook.c:180:34: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  180 |     addr = (addr && (0x4550U == *(uint32_t *)addr))? addr:0; \
      |                                  ^
../../fxlib/fxhook.c:183:5: note: in expansion of macro 'TICK_HOOK'
  183 |     TICK_HOOK(0);
      |     ^~~~~~~~~
../../fxlib/fxhook.c:182:51: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  182 |     HookPatchTimer(addr, patch, si.dwPageSize - (((uint32_t)patch) & (si.dwPageSize - 1)));
      |                                                   ^
../../fxlib/fxhook.c:183:5: note: in expansion of macro 'TICK_HOOK'
  183 |     TICK_HOOK(0);
      |     ^~~~~~~~~
cc1.exe: all warnings being treated as errors
make: *** [Makefile:63: fxlib] Error 1`

**Comment by kjliew** [comment]
If you were compiling from MSYS2, then the error seemed like you were not in MINGW32 environment. Exercise some common sense, this is guest stuffs and it needs to target WIN32. You must have changed the Makefile, otherwise, it would have flagged an error when `MSYSTEM != MINGW32`. The recommendation to change the Makefile is only meant for Linux cross-compiling which I don't that myself. Don't just blindly follow any instructions.

You won't get any of those errors compiling from MSYS2 if you hadn't touched the Makefile. This is my native environment that I use it everyday on Windows 10.

**Comment by mr-falafel** [comment]
Thanks for the help. I haven't touched the makefile at all. You're right, though. I was using mingw64. That's my bad...
I managed to find and install mingw-w64-cross-toolchain and that allowed the mesa wrapper to build. From what I could see online that package includes gendef, which has replaced pexports in MSYS2? If that is the case, maybe the readme should clarify that. However, trying to build the 3dfx wrapper results in the below. I think this is to do with i686-pc-msdosdjgpp/dxe3gen. I'm not sure how to meet that dependency within MSYS2 so any help in that regard would be wonderful.

Result of make && make clean:
`$ make && make clean
  CC  fxhook.o fxlib9x.o fxlibnt.o
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="0a34169-" -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base -Wl,--dynamicbase -Wl,--nxcompat
  RC  glide_res.o
  LD  glide.dll
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="0a34169-" -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base -Wl,--dynamicbase -Wl,--nxcompat
  RC  glide2x_res.o
  LD  glide2x.dll
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="0a34169-" -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base -Wl,--dynamicbase -Wl,--nxcompat
  RC  glide3x_res.o
  LD  glide3x.dll
make[1]: Entering directory '/home/sky/myqemu/qemu-3dfx/wrappers/3dfx/dxe'
  CC  glidedxe.o
make[1]: i686-pc-msdosdjgpp-gcc: No such file or directory
make[1]: *** [Makefile:29: glidedxe.o] Error 127
make[1]: Leaving directory '/home/sky/myqemu/qemu-3dfx/wrappers/3dfx/dxe'
make: *** [Makefile:23: fxdrv] Error 2`

**Comment by kjliew** [comment]
Building OVL/DXE wrappers for DOS/DJGPP requires additional toolchain setup. You should use DOSBox for DOS games. You can build only the Windows DLLs with `$ make fxlib glide2x.dll glide3x.dll glide.dll && make clean`

**Comment by mr-falafel** [comment]
Thank you again, that's great. DOSBox and PCem already meet my DOS needs so I'm not too worried about that. All of the dlls are building fine but I'm not sure fxlib is. I'm not getting errors but I also don't have FXMEMMAP.VXD or FXPTL.SYS, which are mentioned in the readme. I'm making the assumption that those are linked to fxlib but I don't know. I also noticed the fxlib directory. Do I need to build in there, too?
I'm also missing INSTDRV.EXE, if that's something I need to compile.

The 3dfx build directory contains:
`libglide2x.dll.a
libglide3x.dll.a
glide.dll
glide2x.dll
glide3x.dll
Makefile`

The mesa build directory contains:
`wglinfo.exe
opengl32.dll
Makefile`

The fxlib directory contains:
`fxhook.c
fxlib9x.c
fxlibnt.c
fxlib.h`

This is the terminal output for the command you gave me, executed in the 3dfx build directory:
`make fxlib glide2x.dll glide3x.dll glide.dll && make clean
  CC  fxhook.o fxlib9x.o fxlibnt.o
  CC  glidedll.o
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="0a34169-" -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base -Wl,--dynamicbase -Wl,--nxcompat
  RC  glide2x_res.o
  LD  glide2x.dll
  CC  gl301dll.o
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="0a34169-" -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base -Wl,--dynamicbase -Wl,--nxcompat
  RC  glide3x_res.o
  LD  glide3x.dll
  CC  gl211dll.o
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="0a34169-" -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base -Wl,--dynamicbase -Wl,--nxcompat
  RC  glide_res.o
  LD  glide.dll
make[1]: Entering directory '/home/sky/myqemu/qemu-3dfx/wrappers/3dfx/dxe'
make[1]: Leaving directory '/home/sky/myqemu/qemu-3dfx/wrappers/3dfx/dxe'
make[1]: Entering directory '/home/sky/myqemu/qemu-3dfx/wrappers/3dfx/ovl'
make[1]: Leaving directory '/home/sky/myqemu/qemu-3dfx/wrappers/3dfx/ovl'
-rwxr-xr-x 1 sky None 52149 May 10 14:02 glide.dll
-rwxr-xr-x 1 sky None 53173 May 10 14:02 glide2x.dll
-rwxr-xr-x 1 sky None 53205 May 10 14:02 glide3x.dll`

**Comment by mr-falafel** [comment]
I managed to find Voodoo3-10700.exe and voodoo3-winnt-10400.exe. Are those the packages you mentioned that have FXMEMMAP.VXD, FXPTL.SYS and INSTDRV.EXE? If so, do I install them within the vm or do I need to extract the files out and place them manually?

**Comment by kjliew** [comment]
Not from Voodoo3, either Voodoo1 or Voodoo2, IIRC. You will have to extract the files out and place them manually.

**Comment by mr-falafel** [comment]
Thank you! I've found everything other than INSTDRV.EXE. Should that be included in the NT package?
I suppose, since I've built the wrappers now, that this issue should be closed.
