### ISSUE TITLE
Error Starting Program

### ISSUE THREAD

**Issue by BPaden** [kjliew/qemu-3dfx#18]
After going through the wiki and enabling KVM I get the following error

```
The SHELL32.DLL file is
linked to missing export SHLWAPI.DLL:tFileAttributesA.
```

Does this indicated I screwed up the startup script bit?

Well I should mention I tried the sigmatel_c-major.exe drivers in the Dell Latitude D600 9x Drivers V2 someone shared on the vogons forums, but I couldn't get it to work. So I installed some realtek drivers from vogonsdrivers instead. I also didn't bother to install ethernet drivers because I don't intend to use them.

**Comment by BPaden** [comment]
NVM, I found the solution here: https://www.reddit.com/r/vmware/comments/ajipga/win98_installation_issue_shlwapidll_missing/

Now that I think about it, I do remember reading back when Ryzen was new that they screwed up 16-bit compatibility somehow.

So for documentation, the solution is to boot into windows without kvm and then go to control panel->system->performance->file system->troubleshooting->disable all 32-bit proteced-mode disk drivers. Then you can reboot with kvm

**Comment by kjliew** [comment]
@BPaden `Disable all 32-bit protected-mode disk drivers` is **NOT a solution** and not required. There is nothing wrong with Ryzen, it's Windows 98 inherent issue on very fast CPUs with MMU paging. If you do not explicitly require Windows 98 VM, then you can use Windows ME VM for Ryzen CPUs. Windows 2000 and XP VMs work equally well if the games are compatible or can be minimally patched to make them work on Windows 2000 and XP.

Though you had the issue closed, this reply was to stop spread of misinformation in case someone read this.

**Comment by BPaden** [comment]
I see. Thank you for the information @kjliew! I will give Windows ME a try. I don't think I've seen it more than once or twice back when it was new so I'm kind of interested now.
