### ISSUE TITLE
current fxmemmap.vxd and glide-dll's as a built bundle?

### ISSUE THREAD

**Issue by WalkingDot** [kjliew/qemu-3dfx#2]
Hello,
unfortunately my distribution doesn't have the necessary packages (e.g. wcc386, i686-pc-msdosdjgpp-gcc) to build the the fxmemmap.vxd and glide-dll's.
Could you please provide the current files as a built bundle?

And many thanks for qemu-3dfx!

**Comment by kjliew** [comment]
Prebuilt Glide guest wrappers binary for DOS/Windows is available at:
https://www.vogons.org/viewtopic.php?p=680830#p680830
