### ISSUE TITLE
Add support for Grover, a new 3dfx Glide API implementation built on Gallium3D

### ISSUE THREAD

**Issue by volkertb** [kjliew/qemu-3dfx#29]
Hi @kjliew,

It looks like Linux may soon be getting an officially supported "native" 3dfx Glide implementation, called "Grover".

This definitely looks like something that would be worth adding support for in your `qemu-3dfx` project. That way, no third party Glide wrapper would be needed any more, at least on Linux hosts. And since it leverages Gallium3D directly, it might be more efficient than something on top of OpenGL as well. Perhaps you can look into this?

See the [news article about Grover on Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=2022-Mesa-Grover).

Thanks. :slightly_smiling_face:

**Comment by kjliew** [comment]
Support from QEMU is considered done. As long as user-space libraries for Glide APIs are provided, there is no difference whether they are OpenGLide or Gallium3D.

**Comment by volkertb** [comment]
So it would get picked up in the same way as an OpenGL ICD (regardless of vendor or underlying hardware) would get picked up by an OpenGL application? I guess that makes sense and that would be great. So all that's left now is to simply try such a set-up?

**Comment by kjliew** [comment]
It does not seem like this will ever land in MESA.

Unfortunate but true, it is more practical to reimplement Glide APIs or improve OpenGLide in the context of modern OpenGL 3.2+ with VBO/VAO/FBO and GLSL for a universal solution among Windows, Linux and macOS.
