### ISSUE TITLE
Failed to compile in arm64 device

### ISSUE THREAD

**Issue by mjuned47** [kjliew/qemu-3dfx#3]
Sorry for noob issue ,im facing error on compiling after applying mesa-glide patch for qemu-4.1.1

/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:142:23: error: initial
izer element is not constant
     WGL_RED_BITS_ARB, pfd.cRedBits,
                       ^~~
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:142:23: note: (near in
itialization for 'iAttribs[17]')
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:143:24: error: initial
izer element is not constant
     WGL_RED_SHIFT_ARB, pfd.cRedShift,
                        ^~~
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:143:24: note: (near in
itialization for 'iAttribs[19]')
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:144:25: error: initial
izer element is not constant
     WGL_GREEN_BITS_ARB, pfd.cGreenBits,
                         ^~~
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:144:25: note: (near in
itialization for 'iAttribs[21]')
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:145:26: error: initial
izer element is not constant
     WGL_GREEN_SHIFT_ARB, pfd.cGreenShift,
                          ^~~
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:145:26: note: (near in
itialization for 'iAttribs[23]')
/home/ad/myqemu/qemu-3dfx/qemu-4.1.1/hw/mesa/mglcntx_linux.c:146:24: error: initial
izer element is not constant
     WGL_BLUE_BITS_ARB, pfd.cBlueBits,

Ubuntu 18.04 via Linux deploy
Im doing this in android device , but got stuck on this last error 
Thanks for help,

**Comment by kjliew** [comment]
https://stackoverflow.com/questions/3025050
Scroll to one of the answers below, it said GCC 8.1 (or later) has extension for using static const as initializer. The code compiled fine on ArchLinux x86_64, so I guess you probably need to check the version of GCC in use.

**Comment by kjliew** [comment]
Closed for lack of activity.

**Comment by mjuned47** [comment]
Thanks 
I compiled successfully with gcc8
But when it gives "segmentation fault" error when i execute
 qemu-system-i386 -hda winxp.qcow2 -display sdl,gl=on

**Comment by mjuned47** [comment]
Dude can you make this workable on android too?
