### ISSUE TITLE
Can't Build the Wrappers

### ISSUE THREAD

**Issue by thePublicer** [kjliew/qemu-3dfx#30]
This is the build log file
[build.log](https://github.com/kjliew/qemu-3dfx/files/8074701/build.log)

**Comment by kjliew** [comment]
You missed the correct setup for build environment to cross build for WIN32. The `conf_wrapper` script should have flagged it. Please include the log from `conf_wrapper`.

**Comment by thePublicer** [comment]
Here's the log, you requested
[conf.log](https://github.com/kjliew/qemu-3dfx/files/8075221/conf.log)

**Comment by kjliew** [comment]
Check your GCC compiler
```
$ gcc -v 2>&1 | grep ^Target
Target: i686-w64-mingw32
```

**Comment by thePublicer** [comment]
Target: x86_64-w64-mingw32

**Comment by kjliew** [comment]
> Target: x86_64-w64-mingw32

Wasn't that already obvious that you didn't have the correct GCC target?

**Comment by thePublicer** [comment]
Ok. I may try cross compiling from Linux.
