### ISSUE TITLE
Build on MacOS M1 failed

### ISSUE THREAD

**Issue by thePublicer** [kjliew/qemu-3dfx#31]
here's the log file of the build
[build.log](https://github.com/kjliew/qemu-3dfx/files/8093889/build.log)

**Comment by kjliew** [comment]
Disable macOS COCOA and enable SDL2 for QEMU.
`--disable-cocoa --enable-sdl`

**Comment by thePublicer** [comment]
here's the 2nd log file of the build
[build.log](https://github.com/kjliew/qemu-3dfx/files/8249141/build.log)

**Comment by kjliew** [comment]
QEMU official build instructions - https://www.qemu.org/download/
Detailed compilation instructions can be found in the wiki for macOS - https://wiki.qemu.org/Hosts/Mac

If you are still having troubles in building, then a small donation to support the project will have the binary packages delivered for you. Details at https://github.com/kjliew/qemu-3dfx#donation
