### ISSUE TITLE
ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.

### ISSUE THREAD

**Issue by Tarentaise** [kjliew/qemu-3dfx#34]
During the configure stage I get this.
```
~/myqemu/qemu-3dfx/build $ ../qemu-6.2.0/configure 

ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
       You probably need to set PKG_CONFIG_LIBDIR
       to point to the right pkg-config files for your
       build target

```

Distro: Gentoo amd64
Crossdevs: i686, i386, arm

**Comment by kjliew** [comment]
The ERROR is loud & clear. Here's the wiki on how to build QEMU for Linux
https://wiki.qemu.org/Hosts/Linux

If you are still having troubles in building, then a small donation to support the project will have the binary packages delivered for you. Details at https://github.com/kjliew/qemu-3dfx#donation
