### ISSUE TITLE
error creating symlinks/files don't exist

### ISSUE THREAD

**Issue by Whatscheiser** [kjliew/qemu-3dfx#38]
Hello,

I'm attempting to follow the documentation in your git but when I make it to the step that calls for "tar xf qemu-6.2.0.tar.xz"
The following is printed in the terminal...
-----------------------------------------------------------------------------

tar: qemu-6.2.0/roms/u-boot/tools/binman/binman: Cannot create symlink to ‘main.py’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/tools/patman/patman: Cannot create symlink to ‘main.py’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/tools/dtoc/dtoc: Cannot create symlink to ‘main.py’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/tools/microcode-tool: Cannot create symlink to ‘microcode-tool.py’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/include/ctype.h: Cannot create symlink to ‘linux/ctype.h’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-mini-emmc1: Cannot create symlink to ‘zynqmp-zcu102-rev1.0’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-m-a2197-03-revA: Cannot create symlink to ‘zynqmp-a2197-revA’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-m-a2197-01-revA: Cannot create symlink to ‘zynqmp-a2197-revA’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-zcu104-revC: Cannot create symlink to ‘zynqmp-zcu104-revA’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-p-a2197-00-revA: Cannot create symlink to ‘zynqmp-a2197-revA’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-mini-qspi: Cannot create symlink to ‘zynqmp-zcu102-rev1.0’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/avnet-ultra96-rev1: Cannot create symlink to ‘zynqmp-zcu100-revC’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-mini: Cannot create symlink to ‘zynqmp-zcu102-rev1.0’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-mini-emmc0: Cannot create symlink to ‘zynqmp-zcu100-revC’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynqmp/zynqmp-g-a2197-00-revA: Cannot create symlink to ‘zynqmp-a2197-revA’: No such file or directory
tar: qemu-6.2.0/roms/u-boot/board/xilinx/zynq/zynq-cse-nand: Cannot create symlink to ‘zynq-zc770-xm011’: No such file or directory
tar: qemu-6.2.0/roms/skiboot/opal-ci/build-fedora-rawhide.sh: Cannot create symlink to ‘build-fedora33.sh’: No such file or directory
tar: qemu-6.2.0/roms/skiboot/opal-ci/build-debian-unstable.sh: Cannot create symlink to ‘build-ubuntu-latest.sh’: No such file or directory
tar: qemu-6.2.0/roms/edk2/EmulatorPkg/Unix/Host/X11IncludeHack: Cannot create symlink to ‘/opt/X11/include’: No such file or directory
tar: Exiting with failure status due to previous errors

--------------------------------------------------------------------------------

I'm on Windows 10 in a MSYS2 environment executing on MinGW x64...

Honestly I'm not even sure if this feedback is significant, but it is the only feedback I am given that denotes an error aside from when I attempt to compile using the make file that fails as well. I'm assuming this is at least part of the reason for that failure.

-----------------------------------------------------------------------------------
Also when running the make command I get the following...
-----------------------------------------------------------------------------------
$ ../qemu-6.2.0/configure && make
ln: failed to create symbolic link 'aarch64-softmmu/qemu-system-aarch64': No such file or directory
ln: failed to create symbolic link 'alpha-softmmu/qemu-system-alpha': No such file or directory
ln: failed to create symbolic link 'arm-softmmu/qemu-system-arm': No such file or directory
ln: failed to create symbolic link 'avr-softmmu/qemu-system-avr': No such file or directory
ln: failed to create symbolic link 'cris-softmmu/qemu-system-cris': No such file or directory
ln: failed to create symbolic link 'hppa-softmmu/qemu-system-hppa': No such file or directory
ln: failed to create symbolic link 'i386-softmmu/qemu-system-i386': No such file or directory
ln: failed to create symbolic link 'm68k-softmmu/qemu-system-m68k': No such file or directory
ln: failed to create symbolic link 'microblaze-softmmu/qemu-system-microblaze': No such file or directory
ln: failed to create symbolic link 'microblazeel-softmmu/qemu-system-microblazeel': No such file or directory
ln: failed to create symbolic link 'mips-softmmu/qemu-system-mips': No such file or directory
ln: failed to create symbolic link 'mips64-softmmu/qemu-system-mips64': No such file or directory
ln: failed to create symbolic link 'mips64el-softmmu/qemu-system-mips64el': No such file or directory
ln: failed to create symbolic link 'mipsel-softmmu/qemu-system-mipsel': No such file or directory
ln: failed to create symbolic link 'nios2-softmmu/qemu-system-nios2': No such file or directory
ln: failed to create symbolic link 'or1k-softmmu/qemu-system-or1k': No such file or directory
ln: failed to create symbolic link 'ppc-softmmu/qemu-system-ppc': No such file or directory
ln: failed to create symbolic link 'ppc64-softmmu/qemu-system-ppc64': No such file or directory
ln: failed to create symbolic link 'riscv32-softmmu/qemu-system-riscv32': No such file or directory
ln: failed to create symbolic link 'riscv64-softmmu/qemu-system-riscv64': No such file or directory
ln: failed to create symbolic link 'rx-softmmu/qemu-system-rx': No such file or directory
ln: failed to create symbolic link 's390x-softmmu/qemu-system-s390x': No such file or directory
ln: failed to create symbolic link 'sh4-softmmu/qemu-system-sh4': No such file or directory
ln: failed to create symbolic link 'sh4eb-softmmu/qemu-system-sh4eb': No such file or directory
ln: failed to create symbolic link 'sparc-softmmu/qemu-system-sparc': No such file or directory
ln: failed to create symbolic link 'sparc64-softmmu/qemu-system-sparc64': No such file or directory
ln: failed to create symbolic link 'tricore-softmmu/qemu-system-tricore': No such file or directory
ln: failed to create symbolic link 'x86_64-softmmu/qemu-system-x86_64': No such file or directory
ln: failed to create symbolic link 'xtensa-softmmu/qemu-system-xtensa': No such file or directory
ln: failed to create symbolic link 'xtensaeb-softmmu/qemu-system-xtensaeb': No such file or directory

**Comment by kjliew** [comment]
### Google is your friend ###
QEMU official build instructions - https://www.qemu.org/download/
Detailed compilation instructions can be found in the wiki for Win32 - https://wiki.qemu.org/Hosts/W32

If you are still having troubles in building, then a small donation to support the project will have the binary packages delivered for you. Details at https://github.com/kjliew/qemu-3dfx#donation

**Comment by Whatscheiser** [comment]
Yeah... I've been googling all day. Google tends to be very helpful when you know what to ask it and are not just throwing vague output from logs at the wall to see what sticks. I've got no experience with qemu, and very little at all compiling software. I guess I incorrectly assumed that your git contained all the pertinent information needed to compile qemu with this patch... since that seems to be the point here.

Anyway thanks for linking qemu's docs. I'll have a sift through that.

I'm enthusiastic about this project but by the look of it, the amount of it you assume to be understood without explanation is a bit puzzling.

**Comment by kjliew** [comment]
It is in wishful thought that one's enthusiasm would have fueled the determination to explore & learn. Otherwise, the option to support the project with a small donation would have offer an easy & zero-frustration way out. It is an unspoken way-of-life for supporting F-O-S-S :smile:

After all, there are always alternatives, VMware, VirtualBox etc. and names that I don't even need to mention. Again, **Google is still your best friend**.

**Comment by Whatscheiser** [comment]
Well I mean, I have spent all day on google as you so adamantly insist I do. I also went through the effort to install a dev environment I had never heard of nor do I have any experience in to build in accordance with the direction you have provided on github. Your patch section is titled "Build QEMU" after all. I also grasped from what the terminal was printing all of the prerequisite packages I needed before I even read the documentation you pointed me to at wiki.qemu.org.

...exactly how much more enthusiastic would you like me to be?

Its not as if this patch of yours has been applied by everyone everywhere. It's a fairly proprietary thing to go to google with when I have no point of reference in the first place outside of your github page and the videos you've posted on youtube. Neither of which are very revealing about much of anything, aside from the fact that cool thing is cool.

I'd be willing to donate to this project and I still may, because like I said, and despite our exchange here, I like the project. 

My issue isn't with compiling QEMU (just did it) or setting up the environment to do so. My issue is understanding how your patch ties into it and why symbolic links are never created for anything despite following every security/group policy article I could find in relation to making Windows play nice with MSYS2. 

I  suppose my next step will be trying to build the package on Linux. Thanks for all of your help.

**Comment by kjliew** [comment]
I thank you in advance for supporting the project.
