### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by mjuned47** [kjliew/qemu-3dfx#4]
I have compiled qemu with enable sdl ,enable opengl 
Also compiled openglide with disable sdl
But when i execute :
qemu-system-i386 -display sdl,gl=on
And 
qemu-system-i386 -display sdl,gl=es
Both gives segmentation fault 
device : arm64 android
Running ubuntu via sparkle app

**Comment by kjliew** [comment]
There wasn't enough details to show that the fault was caused by the new code addition. You could just have a broken QEMU build with or without the patch. Test the pristine QEMU build first before opening an issue here.

**Comment by mjuned47** [comment]
i got following running qemu inside gdb

0x0000005555b75cfc in glide_gui_getwidth () at ui/sdl2.c:786
#1  0x00000055558c5c10 in init_window (res=7, wndTitle=wndTitle@entry=0x5557056d78 "Glide 2.45 - OpenGLide 0.09rc9") at /root/qemu-4.1.1/hw/3dfx/glidewnd.c:227
#2  0x00000055558c301c in processArgs (s=s@entry=0x5557056700)
    at /root/qemu-4.1.1/hw/3dfx/glidept_mm.c:281
#3  0x00000055558c4278 in glidept_write (opaque=0x5557056700, addr=<optimized out>, val=76, size=<optimized out>) at /root/qemu-4.1.1/hw/3dfx/glidept_mm.c:928
#4  0x0000005555892f2c in memory_region_write_accessor (mr=0x5557056a10, addr=4032, value=<optimized out>, size=4, shift=<optimized out>, mask=<optimized out>, attrs=...)
    at /root/qemu-4.1.1/memory.c:508
#5  0x0000005555890afc in access_with_adjusted_size (addr=addr@entry=4032, value=value@entry=0x7f9fc9eb28, size=size@entry=4, access_size_min=<optimized out>, access_size_max=<optimized out>, access_fn=access_fn@entry=
    0x5555892e88 <memory_region_write_accessor>, mr=mr@entry=0x5557056a10, attrs=attrs@entry=...) at /root/qemu-4.1.1/memory.c:574
#6  0x0000005555895438 in memory_region_dispatch_write (mr=mr@entry=0x5557056a10, addr=addr@entry=4032, data=<optimized out>, data@entry=76, size=size@entry=4, attrs=...)
    at /root/qemu-4.1.1/memory.c:1502
#7  0x00000055558a204c in io_writex (env=<optimized out>, mmu_idx=1, val=76, addr=<optimized out>, retaddr=548241159364, size=4, iotlbentry=<optimized out>, iotlbentry=<optimized out>) at /root/qemu-4.1.1/accel/tcg/cputlb.c:950
#8  0x0000007fa5b837a4 in code_gen_buffer ()
#9  0x00000055558bbe2c in cpu_tb_exec (itb=<optimized out>, cpu=0x55565dd590)
    at /root/qemu-4.1.1/accel/tcg/cpu-exec.c:173
#10 0x00000055558bbe2c in cpu_loop_exec_tb (tb_exit=<synthetic pointer>, last_tb=<synthetic pointer>, tb=<optimized out>, cpu=0x55565dd590)
    at /root/qemu-4.1.1/accel/tcg/cpu-exec.c:621
#11 0x00000055558bbe2c in cpu_exec (cpu=cpu@entry=0x55565dd590)
    at /root/qemu-4.1.1/accel/tcg/cpu-exec.c:732
#12 0x0000005555885aac in tcg_cpu_exec (cpu=0x55565dd590)
    at /root/qemu-4.1.1/cpus.c:1435
#13 0x0000005555887dc0 in qemu_tcg_rr_cpu_thread_fn (arg=arg@entry=0x55565dd590)
    at /root/qemu-4.1.1/cpus.c:1537
#14 0x0000005555c6cfe8 in qemu_thread_start (args=<optimized out>)
    at util/qemu-thread-posix.c:502
#15 0x0000007fb74b3088 in start_thread (arg=0x7fffffeb5f) at pthread_create.c:463
#16 0x0000007fb74234ec in thread_start ()
    at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

**Comment by kjliew** [comment]
Android has a different display binding from typical Linux X11/Wayland. I am not familiar with SDL2 Android. There is no official QEMU support for Android. If you patched QEMU to handle Android native display binding, then you should figure out how to do the same for codes that rely on official QEMU source for display plumbing.
