### ISSUE TITLE
I just compiled on Windows10 Host

### ISSUE THREAD

**Issue by daerlnaxe** [kjliew/qemu-3dfx#40]
I'm not sure it's windows 10 host compatible, i looked at your video i think you did some with windows10 host.

I compiled with instructions with msys2 (i don't have habit to use such a compiler, i use visual studio, eclipse and some others IDE), i encouter some problems but with pacman -S <missing package> most of them were resolved. At the end somebody helped me because i was stuck at "ERROR: Unrecognized host OS (uname -s reports 'MINGW64_NT-10.0-19044')".

I never compiled a QEMU before in addition, he gave me this page: https://wiki.qemu.org/Hosts/W32#Native_builds_with_MSYS2
I made:
- pacman -Syu (was ok)
- pacman -Su (was ok)
- pacman -S base-devel mingw-w64-x86_64-toolchain git python ninja 
- pacman -S mingw-w64-x86_64-glib2 mingw64/mingw-w64-x86_64-gtk3 mingw64/mingw-w64-x86_64-SDL2 python-setuptools (i installed all, just in case).

It compiled but when i ran qemu-system-x86_x64 it asked me for libzstd.dll... Was a bit boring because of all the automatic generated pages that don't answer really to the problem, but at the end i found the github project.

I added dll at the root of the qemu-3dfx project, this time it was ok but...
![2022-03-22_10h57_08](https://user-images.githubusercontent.com/18460858/159467851-885dbc39-1401-4154-95e7-972dbb4d80e0.png)

for the x64 dll, i have this message
![2022-03-22_10h59_39](https://user-images.githubusercontent.com/18460858/159467884-bbfba292-b616-42b2-8734-efc34b94e6af.png)

I probably missed something but i don't what... 

I just currently compile the qemu base to see in compareason... I would to see if it works on w10 to make a tutorial in my language. I promote to using QEMU with ShaderGlass for win9x games, some people would to play also with a 3dfx (i'm not sure to wanting to do it, i just played on P.O.D there is few weeks and it's totally outdated, sadly... even if i have really good souvenirs with my pal in lan parties, it's not a game i will play again). 

Sorry for my English-writing and my screenshots, as you can see i'm French.

**Comment by kjliew** [comment]
Making a small donation to support the project would have ridden you from the frustration to troubleshoot QEMU build issues. Details at https://github.com/kjliew/qemu-3dfx#donation

**Comment by daerlnaxe** [comment]
ok, and i will probably do it.
But .. 

- 1st, i'm broke, seriously... even if i made some programs this years (far from what you did, it's impressive) for free, i understand  what you feel, at a moment you want to earn money according  the time you worked.
- 2nd, in all cases i will never pay for something if i'm not sure it's what i search, and if it works as i want.
Example with PCEM, it's wonderful in video but most of time, currently it's not a good idea to use it beyond a 133/166 proc.

Then, too bad in this case, perhaps i will find by myself, perhaps not. Your answer is not a problem if i resolve problems of my life AND i compile by myself (and it's what i search), i will make a donation. Currently i can't afford a suit to search a job ;D then 60$ it's impossible... 

I'm a baker for Minecraft, Shenmue 3 (Alexandre CODOUL, you can verify), and Formula Fusion. I'm ok with the fact some projects deserve money, and talents deserve to explode. But life doesn't like guys like me, all my money served to live during 8 years without a job with near 6 months a year during 8 years when i was K.O.. at the point i don't even remember souvenirs with my daughter. Some people shit money to buy golden shoes... some others would change the world, Elon Musk launch a car in space he could pay for things like this, but when you are a star you must act like a star, right ?

But whatever, i understand, take care of yourself.

Best regards.

**Comment by daerlnaxe** [comment]
Just to understand, perhaps i was wrong you were talking about 60$ or just a donation ?
I said i'm broke, what is true, because i thought you was talking about giving 60$, and currently i can't. Furthermore if i don't know if it will work.  If by small you mean the basic donation it's obvious i can, then i think it's normal in this case.

More, as i've alreay said if it works, the first day i get money i will make the 60$ donation. because i think it's important to preserve old games. And i want, as i said also,  (if it works) promote qemu and your work as the best solution for retrogaming with windows 98's games.

if i was wrong i apologize, i was sure by "small" you were talking about 60$ currently it's not small for me.
