### ISSUE TITLE
Building QEMU under Windows 10 problem

### ISSUE THREAD

**Issue by OSH1980** [kjliew/qemu-3dfx#41]
Well. I'm trying to compile QEMU under Windows 10. I downloaded source, patched, did everything what is described in attached instruction, but I got such message:

[1329/1588] Linking target qemu-system-i386.exe
FAILED: qemu-system-i386.exe
"c++" "-m64" "-mcx16" @qemu-system-i386.exe.rsp
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libqemu-i386-softmmu.fa.p/softmmu_vl.c.obj: in function `feature':
D:\source\build/../softmmu/vl.c:826: undefined reference to `ALIGNED'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:162: run-ninja] Error 1
make[1]: Leaving directory '/d/source/build'
make: *** [GNUmakefile:11: all] Error 2
I have any clue, what's going on…

[qemu_compilation_guide_2 (1).txt](https://github.com/kjliew/qemu-3dfx/files/8405548/qemu_compilation_guide_2.1.txt)

**Comment by kjliew** [comment]
You might have missed the step to sign the QEMU source with GIT commit ID using `sign_commit`. Here's the example output from the script when the source was signed correctly.
```
$ bash ../scripts/sign_commit
a1ed1ca-
./hw/3dfx/g2xfuncs.h:    const char rev_[] = "a1ed1ca-"
./hw/mesa/mglfuncs.h:    const char rev_[] = "a1ed1ca-"
./softmmu/vl.c:    const char rev_[] = "a1ed1ca-"
```

**Comment by daerlnaxe** [comment]
I compiled 6.2 by the method given on the home page of qemu-3dfx project and directly with git clone, but i don't know if i can help you because your qemu compilation guide talk about an older version.  There is a reason ?

**Comment by OSH1980** [comment]
Hey. I wasn't aware, I can use the same compilation script for Linux and for Windows. Everything was compiled successfully. One small suggestion for KJ: can you add parameters for „make”? Without it, compilation ist very long, because it will built all QEMU versions for all plattforms. I know, I can add targetlist parameter, but not all know this.  But I have other questions, so I open new issue. This can be closed.
