### ISSUE TITLE
WHPX issue

### ISSUE THREAD

**Issue by OSH1980** [kjliew/qemu-3dfx#44]
Ok. I can't go further. Compiled QEMU, installed Win98SE. after start I see this:

D:\msys64\home\Admin\qemu\qemu-3dfx\build\qemu-system-i386: WHPX: Failed to emulate MMIO access with EmulatorReturnStatus: 2
D:\msys64\home\Admin\qemu\qemu-3dfx\build\qemu-system-i386: WHPX: Failed to exec a virtual processor

And exiting. What's going on? I have Intel i5 10400F, Windows 10 HP 
Windows Hypervisor Plattform is enabled, Intel Virtualization Technology in BIOS too. 
I tried with kernel-irqchip=off, but it didn't help. Without WHPX start without problems.

**Comment by kjliew** [comment]
**QEMU general usability issues are out of scope of this project.**
