### ISSUE TITLE
DgVoodoo files location

### ISSUE THREAD

**Issue by OSH1980** [kjliew/qemu-3dfx#47]
I'm looking for an instruction where I should put DGVoodoo files under host W10. I downloaded 2.78 version and I see four directories: MS, Doc, CPl and 3dfx. MS, Cpl and 3dfx directories contains subdirectories arm64, x64 and x86. So where I should put these files and which files, if I want to launch a game which requires glide, and  which requires D3D?

**Comment by kjliew** [comment]
You can put dgVoodoo2 files anywhere and make QEMU find them using BASH runscript on Windows 10. Just make sure that the **pathname contains no SPACE** for simple script without having to deal with delimiters. 

Here's an example
```
$ cd ~/myqemu
$ unzip -d dgv2 ~/Downloads/dgVoodoo2_78.zip
$ cp -vf dgv2/dgvoodoo.conf dgv2/3Dfx/x64/
$ cd ~/myqemu/qemu-3dfx/build
$ PATH=$PATH:../../dgv2/3Dfx/x64 ./qemu-system-i386 -M pc,accel=whpx,kernel-irqchip=off \
  -drive file=../vmimgs/w98.qcw \
  -drive file=../vmimgs/mygames.qcw
```
**Make sure there is no other `Glide.dll`, `Glide2x.dll` or `Glide3x.dll` in the search $PATH.**
.
Only the **Glide libraries** from dgVoodoo2 are useful for QEMU as direct replacement of OpenGLide as the **Host Glide wrappers**. The DirectX wrapping libraries from dgVoodoo2 require DirectX11/12 and have no use for QEMU in either **Host** or **Guest** context.

**Comment by OSH1980** [comment]
Thanks KJ! I'll check it!
