### ISSUE TITLE
CTD after Unreal start

### ISSUE THREAD

**Issue by OSH1980** [kjliew/qemu-3dfx#48]
Well I'm trying to launch first Unreal under Ubuntu 20.04 host and Win 98SE guest. 
after start I see a black screen, and then CTD.
In Terminal I see:
`GLIDE_DLL=/usr/local/lib
glidept: DLL loaded - glide2x.dll
trace: _grGlideGetVersion@4 called
glidept: grGlideGetVersion  Glide 2.45 - OpenGLide 0.09rc9
trace: _grSstQueryBoards@4 called
trace: _grGlideInit@0 called
glidept: a1ed1ca-22:36:12 Mar 20 2022 build WRAPFX32
wr2x_trace: _grErrorSetCallback@4                                           
wr2x_trace: _grSstQueryHardware@4                                           
wr2x_trace: _grTexMaxAddress@4                                              
wr2x_trace: _grTexMinAddress@4                                              
wr2x_trace: _grSstSelect@4                                                  
glidept: grSstWinOpen called, fmt 1 org 0 buf 3 aux 1 gLfb 0xcd0c3000
wr2x_trace: _grSstWinOpen@28                                                
glidept: LFB mode is Shared Memory (fast), One-copy
    FBConfig id 0x0a5 visual 0x021 swapNone
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x1aef4180
  Serial number of failed request:  33
  Current serial number in output stream:  37
`
It's interesting, under Windows I have no problem with this, game starts without problems. I'm stuck.

**Comment by kjliew** [comment]
When you recompiled OpenGlide from `qemu-xtra`, removed the `--disable-sdl` for Linux.
Or, use OpenGL renderer for Unreal. It is better than 3Dfx Glide.

**Comment by OSH1980** [comment]
Yes, KJ, it works. Thanks!

**Comment by OSH1980** [comment]
That's great KJ!. I see, you have changed some files, so I have to compile QEMU from scratch.
