### ISSUE TITLE
rsync error on Win10

### ISSUE THREAD

**Issue by DSN9990** [kjliew/qemu-3dfx#49]
Hi all, I'm new to qemu-3dfx and I'm currently learning.

I'm getting this error when trying to compile on my Windows 10 1909 host using msys2 mingw64:

`C:/msys64/usr/bin/rsync.exe: error while loading shared libraries: cygxxhash-0.dll: cannot open shared object file: No such file or directory`

This seems it can't find cygxxhash-0.dll in the shared folder. How can I fix that? Do I need to install anything? Thanks :)

**Comment by kjliew** [comment]
Build environment issues are irrelevant to this project. **Google is your best friend.**
