### ISSUE TITLE
CTD after install new OpenGlide libraries

### ISSUE THREAD

**Issue by OSH1980** [kjliew/qemu-3dfx#50]
I compiled newest OpelnGlide libraries (without --disableand wrappers, installed it and now after I launch Unreal or even test04.exe, i have instant CTD. And I got a message:
 
`glidept: DLL loaded - glide2x.dll
trace: _grGlideGetVersion@4 called
glidept: grGlideGetVersion  Glide 2.45 - OpenGLide 0.09rc9
trace: _grSstQueryBoards@4 called
trace: _grGlideInit@0 called
glidept: d74c897-13:18:01 May 12 2022 build WRAPFX32
wr2x_trace: _grErrorSetCallback@4                                           
wr2x_trace: _grSstQueryHardware@4                                           
wr2x_trace: _grSstSelect@4                                                  
glidept: grSstWinOpen called, fmt 1 org 0 buf 3 aux 1 gLfb 0xcd2c7000
wr2x_trace: _grSstWinOpen@28                                                
./qemustart.sh: Zeile 10: 74394 Speicherzugriffsfehler  (Speicherabzug geschrieben) LD_LIBRARY_PATH=$GLIDE_DLL $QEMU -L /home/nemezis/Emulatory -rtc base=localtime -no-hpet -display sdl -no-reboot -drive file=/media/nemezis/WORK/Emulatory/win98.qcow2 -drive file=/media/nemezis/WORK/Emulatory/win982.qcow2 -device VGA -M pc,accel=kvm -device ac97 -netdev user,id=net0 -device rtl8139,netdev=net0 -drive if=floppy,file=/home/nemezis/Emulatory/Win98SE.img,format=raw,index=0,media=disk -cdrom /dev/sr1 -usb -device usb-host,hostbus=1,hostaddr=13 -usb -device usb-host,hostbus=1,hostaddr=10 $@`

"Speicherzugrifffehler" = "memory access error". I'm stuck as always.
Ubuntu 20.04

Now I compiled prevoius version of OpenGlide - and it works flawlessly. So the problem is with newest version…

**Comment by brunocastello** [comment]
Now that you mentioned it, your problem is similar to mine here on macOS, the OpenGlide only works flawlessly if I compile from this commit: https://github.com/kjliew/qemu-xtra/commit/d0a0914ddb7a41cc5103c289ec302e4692c23b34 then subsequent commits will compile too, but qemu-3dfx will crash to terminal whenever I attempt to run a game with glide.

**Comment by kjliew** [comment]
Works fine here with `TEST04.EXE`
ArchLinux x86_64
```
QEMU emulator version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
  featuring qemu-3dfx@0c9630c-13:42:25 May 12 2022 build

DARTH@TheEMPIRE wayland ~/src/qemu/build
$ glidept: DLL loaded - glide2x.dll
trace: _grGlideGetVersion@4 called
glidept: grGlideGetVersion  Glide 2.45 - OpenGLide xtra@9541378
trace: _grGlideInit@0 called
glidept: 0c9630c-20:51:51 May 11 2022 build WRAPFX32
wr2x_trace: _grSstQueryHardware@4                                           
wr2x_trace: _grSstSelect@4                                                  
glidept: grSstWinOpen called, fmt 1 org 0 buf 2 aux 1 gLfb 0xfb000000
wr2x_trace: _grSstWinOpen@28                                                
glidept: LFB mode is Shared Memory (fast), One-copy
Info: Mesa Intel(R) Xe Graphics (TGL GT2) OpenGL 4.6 (Compatibility Profile) Mesa 22.0.3
Info: Pixel Format ABGR8888 D24S8 nAux 0 nSamples 0 0 
     window 640x480 
glidept: grSstWinClose called                                            
glidept: grGlideShutdown called, fifo 0x00be data 0x0dae shm 0x00436b8 lfb 0xfb000000
glidept:   GrState 1 VtxLayout 0
glidept: DLL unloaded
```

**Comment by OSH1980** [comment]
KJ QEMU 7.0.0? But we hadn't  mesa-glide patch for 7.0.0 yet…

**Comment by kjliew** [comment]
The version isn't very important. After all, in practice of [⚡FORCE LIGHTING⚡], any version is just a lightning strike away.🤣

The key message is `qemu-3dfx@0c9630c` and `OpenGLide xtra@9541378`.

**Comment by OSH1980** [comment]
KJ, Still no luck. I can't understand this, really. I clone your OpenGlide repo, compile, then install. I installed also compiled Glide.dll, Glide2x.dll and Glide3x.dll in Windows\system directory. Unreal starts, but doesn't detect 3dfx and run in window.

**Comment by kjliew** [comment]
>clone your OpenGlide repo, compile, then **install**

The freedom of Linux can be a curse. Did you ever notice where OpenGlide libs were installed to?

Usually, one needs to provide `--prefix=` for the installation to place the solib into somewhere loadable by dlopen(). The recent development in secure computing would restrict that to /lib or /usr/lib for most modern Linux distros but the default for `"configure && make"` without `--prefix=` is /usr/local.

Your QEMU binary package for Ubuntu 20.04 comes with a run script that uses **LD_LIBRARY_PATH** override for dlopen() to load solib. There is no need to install OpenGlide.

**Comment by OSH1980** [comment]
Ok, I pointed this variable to directory with solibs - the same situation.

**Comment by kjliew** [comment]
@OS1980 How did it ever work for you then in issue #48 ?

**Comment by OSH1980** [comment]
Well, after I removed „--disable-sdl” parameter and compiled, it worked. But now, even without this parameter it doesn't work…

**Comment by kjliew** [comment]
@OSH1980 Please try again on latest `qemu-3dfx` and `qemu-xtra` from a fresh start. If it had worked for you in issue #48, then it should work again. Otherwise, you should include the console log to get help just like how you started in the first place. The log is always **critical and gives valuable insights** for support.

**No log = No support.**

**Comment by OSH1980** [comment]
Ok KJ. After long battle, it finally works. But only with QEMU 6.2.0. Under 7.0.0 I cant activate Glide. And you have mentioned log - how can I generate it?

**Comment by kjliew** [comment]
Great, so problem solved.

**Comment by brunocastello** [comment]
> Ok KJ. After long battle, it finally works. But only with QEMU 6.2.0. Under 7.0.0 I cant activate Glide. And you have mentioned log - how can I generate it?

Could you explain how you solved it, please? For me the latest version of his OpenGlide doesn't work, only from the commit I mentioned above it works.

**Comment by kjliew** [comment]
@brunocastello Works fine on MacBook Air M1, too.
```
QEMU emulator version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
  featuring qemu-3dfx@bb591d9-18:20:30 May 14 2022 build

AppleMacBook-Air: ~/src/qemu/build
$ glidept: DLL loaded - glide2x.dll
trace: _grGlideGetVersion@4 called
glidept: grGlideGetVersion  Glide 2.45 - OpenGLide xtra@9541378
trace: _grGlideInit@0 called
glidept: bb591d9-15:19:34 May 13 2022 build WRAPFX32
wr2x_trace: _grSstQueryHardware@4                                           
wr2x_trace: _grSstSelect@4                                                  
glidept: grSstWinOpen called, fmt 1 org 0 buf 2 aux 1 gLfb 0xfb000000
wr2x_trace: _grSstWinOpen@28                                                
glidept: LFB mode is Shared Memory (fast), One-copy
Info: Apple M1 OpenGL 2.1 Metal - 76.3
Info: Pixel Format ABGR8888 D32S8 nAux 0 nSamples 0 0 
     window 640x480 
glidept: grSstWinClose called                                            
glidept: grGlideShutdown called, fifo 0x00be data 0x0dae shm 0x00436b8 lfb 0xfb000000
glidept:   GrState 1 VtxLayout 0
glidept: DLL unloaded
```

**Comment by OSH1980** [comment]
> > Ok KJ. After long battle, it finally works. But only with QEMU 6.2.0. Under 7.0.0 I cant activate Glide. And you have mentioned log - how can I generate it?
> 
> Could you explain how you solved it, please? For me the latest version of his OpenGlide doesn't work, only from the commit I mentioned above it works.

Actually I haven't any idea. Problem is with one file: glide2x.dll. If I generate it from newest repo - then it won't work. If I generate it from older repo - it works. I tried to compare files from "3dfx" directory for both versions, but I can't find, which files are modified.

**Comment by brunocastello** [comment]
The only thing different here could be the SDL2 version. Which version are you guys at? I’m at latest

**Comment by OSH1980** [comment]
> The only thing different here could be the SDL2 version. Which version are you guys at? I’m at latest, all my homebrew packages are up to date.

Here's mine:
ii  libsdl-image1.2:amd64                         1.2.12-12                             amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2debian:amd64                         1.2.15+dfsg2-5                        amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                           2.0.10+dfsg1-3                        amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:i386                            2.0.10+dfsg1-3                        i386         Simple DirectMedia Layer
ii  libsdl2-dev:amd64                             2.0.10+dfsg1-3                        amd64        Simple DirectMedia Layer development files
ii  libsdl2-net-2.0-0:amd64                       2.0.1+dfsg1-4                         amd64        Network library for Simple DirectMedia Layer 2, libraries

**Comment by brunocastello** [comment]
You seem to be on 2.0.10, mine is 2.0.22

**Comment by OSH1980** [comment]
So we have to wait for KJ answer.

**Comment by kjliew** [comment]
"What is thy bidding, my master?"
"There is a great disturbance in the Force."
"I have felt it."
-- DARTH VirtJerk & Mystery SITH with Dark Forces II discuss @brunocastello

**Comment by brunocastello** [comment]
@OSH1980 are you on any forum or whatever?

**Comment by brunocastello** [comment]
@OSH1980 whats your handle on VOGONS? I can pm you.

**Comment by OSH1980** [comment]
OSH :D

**Comment by OSH1980** [comment]
You have disabled reply function on VOGONS.

**Comment by brunocastello** [comment]
> You have disabled reply function on VOGONS.

oh sorry. wait a minute

**Comment by brunocastello** [comment]
> @brunocastello Works fine on MacBook Air M1, too.
> 
> ```
> QEMU emulator version 7.0.0
> Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
>   featuring qemu-3dfx@bb591d9-18:20:30 May 14 2022 build
> 
> AppleMacBook-Air: ~/src/qemu/build
> $ glidept: DLL loaded - glide2x.dll
> trace: _grGlideGetVersion@4 called
> glidept: grGlideGetVersion  Glide 2.45 - OpenGLide xtra@9541378
> trace: _grGlideInit@0 called
> glidept: bb591d9-15:19:34 May 13 2022 build WRAPFX32
> wr2x_trace: _grSstQueryHardware@4                                           
> wr2x_trace: _grSstSelect@4                                                  
> glidept: grSstWinOpen called, fmt 1 org 0 buf 2 aux 1 gLfb 0xfb000000
> wr2x_trace: _grSstWinOpen@28                                                
> glidept: LFB mode is Shared Memory (fast), One-copy
> Info: Apple M1 OpenGL 2.1 Metal - 76.3
> Info: Pixel Format ABGR8888 D32S8 nAux 0 nSamples 0 0 
>      window 640x480 
> glidept: grSstWinClose called                                            
> glidept: grGlideShutdown called, fifo 0x00be data 0x0dae shm 0x00436b8 lfb 0xfb000000
> glidept:   GrState 1 VtxLayout 0
> glidept: DLL unloaded
> ```

Not on my side. A few commits ago it was working, now its not anymore.  Unless OpenGlide has to be compiled and installed BEFORE compiling qemu-3dfx and its glide wrappers (which does not make any sense at all), I cannot see why it refuses to work.
