### ISSUE TITLE
QEMU 7 support?

### ISSUE THREAD

**Issue by demberto** [kjliew/qemu-3dfx#51]

**Comment by kjliew** [comment]
QEMU 7 support is available with a small donation to support the project. Details at https://github.com/kjliew/qemu-3dfx#donation. The binary package always include the most recent official stable release from upstream QEMU at time of donation.

**Comment by demberto** [comment]
Wow, thanks

**Comment by kjliew** [comment]
Anyone familiar with GNU diff/patch syntax can always merge the changes by hand regardless of QEMU versions.
