### ISSUE TITLE
Bunch of symbol not defined errors when building wrappers

### ISSUE THREAD

**Issue by OldieButGoldie** [kjliew/qemu-3dfx#54]
Building wrappers is simply not possible with provided instructions. I do not intend to build the OVL/DXE wrapper, just the W98 ones.
I have just installed mingw-w64-i686-toolchain and using the MINGW32 environment. QEMU build completed successfully

Info about build system:

```
$ gcc -v 2>&1 | grep "^Target"
Target: i686-w64-mingw32
```

Configure log:
```
$ bash ../../../scripts/conf_wrapper
checking for make... /usr/bin/make
checking for sed... /usr/bin/sed
checking for xxd... /usr/bin/xxd
checking for pexports... /usr/bin/pexports
checking for shasum... /usr/bin/core_perl/shasum
checking for git... /usr/bin/git
  MSYSTEM=MINGW32
  Target: i686-w64-mingw32
-- DOS32 OVL not supported --
-- DJGPP DXE not supported --
conf_wrapper: creating Makefile
```

But when doing make....

3DFX:
<details><pre><code>$ make
  CC  fxhook.o fxlib9x.o fxlibnt.o
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="bb591d9-" -Wall -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base,--no-seh,--dynamicbase,--nxcompat
  RC  glide_res.o
  LD  glide.dll
 * [glide.dll] Found PE image
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAADrawLine@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAADrawPoint@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAADrawPolygon@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAADrawPolygonVertexList@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAADrawTriangle@24@24: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAlphaBlendFunction@16@16: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAlphaCombine@20@20: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAlphaControlsITRGBLighting@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAlphaTestFunction@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grAlphaTestReferenceValue@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grBufferClear@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grBufferSwap@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grChromakeyMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grChromakeyValue@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grClipWindow@16@16: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grColorCombine@20@20: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grColorMask@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grConstantColorValue4@16@16: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grConstantColorValue@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grCullMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDepthBiasLevel@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDepthBufferFunction@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDepthBufferMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDepthMask@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDitherMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDrawLine@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDrawPlanarPolygon@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDrawPlanarPolygonVertexList@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDrawPoint@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDrawPolygon@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDrawPolygonVertexList@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grDrawTriangle@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grErrorSetCallback@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grFogColorValue@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grFogMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grFogTable@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grGammaCorrectionValue@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grGlideGetState@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grGlideGetVersion@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grGlideSetState@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grGlideShamelessPlug@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grHints@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbBypassMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbConstantAlpha@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbConstantDepth@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbGetReadPtr@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbGetWritePtr@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbOrigin@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbWriteColorFormat@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbWriteColorSwizzle@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grLfbWriteMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grRenderBuffer@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstConfigPipeline@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstOpen@24@24: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstOrigin@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstPassthruMode@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstPerfStats@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstQueryBoards@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstQueryHardware@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstSelect@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grSstVidMode@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexCalcMemRequired@16@16: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexClampMode@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexCombine@28@28: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexCombineFunction@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexDetailControl@16@16: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexDownloadMipMap@16@16: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexDownloadMipMapLevel@32@32: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexDownloadMipMapLevelPartial@40@40: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexDownloadTable@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexDownloadTablePartial@20@20: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexFilterMode@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexLodBiasValue@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexMaxAddress@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexMinAddress@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexMipMapMode@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexMultibase@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexMultibaseAddress@20@20: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexNCCTable@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexSource@16@16: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTexTextureMemRequired@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export grTriStats@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export gu3dfGetInfo@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export gu3dfLoad@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guAADrawTriangleWithClip@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guAlphaSource@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guColorCombineFunction@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guDrawPolygonVertexListWithClip@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guDrawTriangleWithClip@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guEndianSwapBytes@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guEndianSwapWords@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guFbReadRegion@24@24: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guFbWriteRegion@24@24: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guFogGenerateExp2@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guFogGenerateExp@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guFogGenerateLinear@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guFogTableIndexToW@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guMPDrawTriangle@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guMPTexCombineFunction@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guMPTexSource@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guMovieSetName@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexAllocateMemory@60@60: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexChangeAttributes@48@48: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexCombineFunction@8@8: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexDownloadMipMap@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexDownloadMipMapLevel@12@12: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexGetCurrentMipMap@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexGetMipMapInfo@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexMemQueryAvail@4@4: symbol not defined
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export guTexSource@4@4: symbol not defined
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:50: glide.dll] Error 1</code></pre></details>

MESA:
https://pastebin.com/r1x3gwRA

**Comment by kjliew** [comment]
>* [glide.dll] Found PE image

I don't get this and I think this is the likely culprit.

My MSYS2/mingw-w64-i686 environment is deliberately kept to be absolutely minimal. Perhaps you can try removing the group meta-package `mingw-w64-i686-toolchain` and re-install with just `mingw-w64-i686-{binutils,gcc}`.

Here's what I have for your reference. Hope it helps.
```
$ pacman -Qs toolchain | grep i686
local/mingw-w64-i686-binutils 2.38-2 (mingw-w64-i686-toolchain)
local/mingw-w64-i686-crt-git 10.0.0.r14.ga08c638f8-1 (mingw-w64-i686-toolchain)
local/mingw-w64-i686-gcc 12.1.0-1 (mingw-w64-i686-toolchain)
local/mingw-w64-i686-gcc-libs 12.1.0-1 (mingw-w64-i686-toolchain)
local/mingw-w64-i686-headers-git 10.0.0.r14.ga08c638f8-1 (mingw-w64-i686-toolchain)
local/mingw-w64-i686-libwinpthread-git 10.0.0.r14.ga08c638f8-1 (mingw-w64-i686-toolchain)
local/mingw-w64-i686-winpthreads-git 10.0.0.r14.ga08c638f8-1 (mingw-w64-i686-toolchain)
```

**Comment by OldieButGoldie** [comment]
Ohh, there seems to be a problem there, `pexports`  seems to be deprecated ([link](https://sourceforge.net/p/mingw-w64/wiki2/gendef/)), and I had to use a shim script as indicated [here](https://postgrespro.com/list/thread-id/2460566).

```
$ which pexports
/usr/bin/pexports
```

```sh
$ cat /usr/bin/pexports
#!/bin/sh
gendef - "$@"
```

However, removing every package from i686 toolchain and installing only binutils & gcc leaves me with no `gendef` (provided by mingw-w64-i686-tools-git)

I'm guessing the output comes from there, when the makefile reads symbols from the .def file if I understand correctly

**Comment by kjliew** [comment]
I just downloaded pexports 0.47 source code and compiled it for MSYS2/mingw-w64-i686. It was included in the old MSYS/MinGW.org before MSYS2/mingw-w64, and I got used to it rather than adapting to gendef.

**Comment by OldieButGoldie** [comment]
Well, that surely did the trick, instead of building yet another thing, I simply downloaded the bin from [here](https://sourceforge.net/projects/mingw/files/MinGW/Extension/pexports/pexports-0.47/), in case there's anyone else with the same problem.

Of course gendef must have changed the output format that made it incompatible with the build script. Thanks for the quick debugging. I myself spent some time looking for the dreaded pexports dependency on msys2 instead of simply look for `pexports`
