### ISSUE TITLE
Extremely Annoying QEMU issues

### ISSUE THREAD

**Issue by uSErDUmp133** [kjliew/qemu-3dfx#55]
is there a workaround for general qemu instability with windows 98 se?
cause its extremely frustating and sometimes it just doesnt feel worth it to use qemu instead of pcem for all the annoying quirks it has with windows 98 se.
i originally intended to use qemu to play the original half life since it definitely has some issues with modern windows nt versions (from 2000 up to 10) like the cd music looping, saves not appearing normally, and not being able to skip the intro normally.

heres a list of the issues i get with qemu:
1. when qemu-3dfx fails to find a glide wrapper for example, qemu forces itself to shut down and causes my windows 98 installation and my files in general (including the games) to most of the time become corrupted which is very annoying since i have to redo the windows 98 installation. (crashing or killing the game instead would be great)

2. qemu sometimes fails to display a screen at times using glide (i dont know if this is an issue with windows 98 locking up or qemu-3dfx failing to do its job)

3. heavy disk reading and writing can cause windows 98 to lock up temporarily over and over especially when trying to copy large files and when using the cd for game music to work (slight micro-stuttering happens in-game which is not too much of an issue for me).
why does qemu have an issue with this but it doesnt seem like vmware or vbox does?

5. using dgvoodoo2 and setting it as full screen at setup makes qemu fail to also display the screen and i have to resort to force-restarting qemu which corrupted the game files sometimes.

6. setting to windowed with dgvoodoo2 and going to full screen with alt-enter works just fine but theres another annoying issue which is if i want to change the game's resolution, go back to the desktop, or go back to the menu which is outside of the game (like half life) and return back to the game then i would get the same annoying issue in the fourth problem (using openglide resolves this but it still seems to be messy because it seems to be in alpha state i assume and also if you have qemu in full screen then start the game then get out of full screen from qemu, the screen will not display the whole thing and it just looks chopped off. same thing happens with opengl32.dll)

7. annoying whpx issues with windows 98 (for example, windows 98 is saying its updating configuration at boot then whpx says portio error something then it says it cant exec a virtual processor and qemu just stops. in kvm, this doesnt seem to happen.)

8. windows 98se also locks up randomly at times (it doesnt happen too much).

9. the pif file for _startup.bat sometimes fails to fix the shut down issue and the same issue happens.

10. sound is sometimes stuttery and sometimes it sounds like previous sounds are overriding current sounds which doesnt seem right (i have used multiple drivers including your modified ac97 driver).

if my pc specs matter then here:
CPU: Intel(R) Core(TM) i5-4460
RAM: 16GB DDR3
GPU: GTX 960 2GB

im not desperate to get these issues solved nor am i asking for much, i just wanted to bring awareness to these issues since its very annoying.
despite all of these issues, qemu works perfectly fine and im thankful for that.

**Comment by uSErDUmp133** [comment]
introducing a built-in fps limiter for opengl, glide, and direct3d can make things a lot easier.
unreal 1998 and unreal tournament 99 runs way too fast on my pc on openglide and opengl.
i dont have this problem in dgvoodoo2 because it already limits the fps.

**Comment by kjliew** [comment]
Just use PCem, VMware or VBox, whichever is less annoying and make you happy.

**No Log == No support**. All the annoying issues do not apply and mostly out of one's inexperience in using QEMU.

For using dgVoodoo2, it is highly recommended to have `Environment = QEmu` in `dgvoodoo.conf`. This also crippled dgVoodoo2 in some of its magics that require WNDPROC hooking that potentially makes QEMU unstable. OTOH, OpenGlide from `qemu-xtra` due to the FOSS nature has seamless integration with QEMU. OpenGL games such as Half-Life 1 are best with MESAGL pass-through rather than 3Dfx miniGL which in turn requires Glide wrappers.

FPS limiter is already there for OpenGL, Glide and Direct3D. For Unreal/UT99, the best option is to enable VSYNC that gives you an all-time locked 60 FPS gameplay. PCem is also another good option, just play at 640x480 with GlideRenderer, it will never have the problem of **"runs way too fast"** on any PC.

Otherwise, a small donation to support the project would have offered a much better experience in using QEMU for retro Windows games. The choice is yours to make.

**Comment by uSErDUmp133** [comment]
i used 3dfx glide in half life for a reason and that is because the decals would abnormally flicker in normal opengl.
a later patch fixed this after release but i wanted to stick with the first build of half life because i wanted to play the whole campaign and try to experience what it was like for people who played it when it first came out.

i have used Environment = QEmu before but i avoided it because the main problem i have with it is that theres so much input lag even in full screen, its not even fun.
i might have to avoid dgvoodoo2 for now.

there doesnt seem to be a vsync option for opengl under unreal 1998 but i just learned that you could create a config file for glide and limit the fps there.
i was not aware of this so thanks.
