### ISSUE TITLE
Requirements plus build error

### ISSUE THREAD

**Issue by AireagoirSteam** [kjliew/qemu-3dfx#57]
Hello having issues finding certain requirements like shasumand pexports for msys2 mingw64.
Was wondering how to get shasum. And if you could also out a github actions build for this repository.

Furthermore I get this error when following the build instructions for applying the patch and building.

C++ Compiler does not support -std=gnu++11

**Comment by kjliew** [comment]
If you are still having troubles in building, then a small donation to support the project will have the binary packages delivered for you. Details at https://github.com/kjliew/qemu-3dfx#donation

**Comment by AireagoirSteam** [comment]
I did get  build with an older version but it had no gpu acceleration like yours does in your videos. So how do I enable this when trying to build myself?

Also the virgil mingw packages also do not build at all since the script can't find libary m
