### ISSUE TITLE
Pył doesn't always start (7.0.0)

### ISSUE THREAD

**Issue by roberttryton** [kjliew/qemu-3dfx#59]
Pył doesn't always initialize glide screen in 7.0.0 after typing pyl.exe and freezes.
To fix that keep enter pressed till screen initializes.

**Comment by kjliew** [comment]
Can you provide the console logs when Pyl didn't start and froze?

**Comment by roberttryton** [comment]
i:\qemu_700_glide_test>qemu-system-i386-700glide.exe -hda MSDOS_win98se.vmdk -au
diodev id=sdl,driver=sdl -machine pcspk-audiodev=sdl -device sb16,audiodev=sdl -
device adlib,audiodev=sdl -device virtio-vga -accel tcg
glidept: DLL loaded - glide2x.dll
trace: _grSstQueryBoards@4 called
trace: _grGlideInit@0 called
glidept: 5abd64f-10:42:35 Jun 24 2022 build WRAPFX32
wr2x_trace: _grSstQueryHardware@4
wr2x_trace: _grSstSelect@4
glidept: grSstWinOpen called, fmt 0 org 0 buf 2 aux 1 gLfb 0xfb000000
wr2x_trace: _grSstWinOpen@28
glidept: LFB mode is Shared Memory (fast), One-copy, LfbLockDirty

**Comment by kjliew** [comment]
No response from OP, considered fixed.

**Comment by roberttryton** [comment]
fixed
by the way, "added a commit that referenced this issue" message doesn't send email so OP doesn't know about it until he checks himself.
