### ISSUE TITLE
OpenGlide is never launched on a Linux host

### ISSUE THREAD

**Issue by misutoneko** [kjliew/qemu-3dfx#6]
I did some testing on Linux Mint 20, here are some observations.
My test case here was test30.exe in a DOS guest (robertmo's boot.7z image from the vogons thread).
The GPU is GTX660, with nvidia proprietary drivers if that matters.

So, when I first launched the guest I found out this:
Commit daa40ac (Oct 22, 2020) added an if clause that seems to stop OpenGlide from ever launching.
(glidept_mm.c line 928 or so, function glidept_write(), case 0xfbc)

I tried removing the code and the execution got then a bit further (OpenGlide.ini and log were created etc.).
It segfaults and has FIFO problems though, so maybe that is what the removed code was trying to avoid...
I got it to run better eventually, by doing some other minor tweaks and recompiling the guest wrapper GLIDE2x.OVL (OpenWatcom v2, had to do some slight alterations to Makefile to get it to compile).

**Comment by kjliew** [comment]
It is to avoid mismatched between QEMU and guest stubs. Guest stubs are already built with commit id. I have added the scripts to synchronize commit id for building QEMU.
