### ISSUE TITLE
BoxV9x driver troubleshooting

### ISSUE THREAD

**Issue by emxd** [kjliew/qemu-3dfx#60]
Apologies if this has been already addressed, but did you change the inf/drv files for the driver to make them work on qemu? I can use VBEMP in qemu and BoxV9x in VirtualBox, but BoxV9x in qemu doesn't work. If so, could you elaborate?

I tried changing the PCI path in the inf from ven_80ee&dev_beef to ven_1234&dev_1111 and recompiled the driver, but that didn't help.

Forgot to mention this, guest OS being Win98SE.

**Comment by kjliew** [comment]
The Bochs dispi implementation has slight differences between VirtualBox and QEMU. They need to be taken care of either in QEMU or BOXV9x/NT.

QEMU VM addons include optional drivers support for QEMU for those who supported & donated to the project.
