### ISSUE TITLE
3dfx wrapper build issue - glideovl.obj missing

### ISSUE THREAD

**Issue by cvbraeuer** [kjliew/qemu-3dfx#61]
Make can not find "glideovl.obj", file does not seem to exist in repo, nor does it get created in the process:

[user@user-standardpcq35ich92009 build]$ bash ../../../scripts/conf_wrapper
checking for make... /usr/bin/make
checking for sed... /usr/bin/sed
checking for xxd... /usr/bin/xxd
checking for pexports... /usr/local/bin/pexports
checking for shasum... /usr/bin/core_perl/shasum
checking for git... /usr/bin/git
  Linux cross build
  CROSS=i686-w64-mingw32-
  CC=gcc
conf_wrapper: creating Makefile

[user@user-standardpcq35ich92009 build]$ make
  CC  fxhook.o fxlib9x.o fxlibnt.o
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="de5c83c-" -Wall -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base,--no-seh,--dynamicbase,--nxcompat
  RC  glide_res.o
  LD  glide.dll
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="de5c83c-" -Wall -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base,--no-seh,--dynamicbase,--nxcompat
  RC  glide2x_res.o
  LD  glide2x.dll
  CFLAGS  -I../../../qemu-0/hw/3dfx -I../../fxlib -D__REV__="de5c83c-" -Wall -Werror -msse2 -O3 -flto -fomit-frame-pointer
  LDFLAGS -static-libgcc -Wl,--disable-auto-image-base,--no-seh,--dynamicbase,--nxcompat
  RC  glide3x_res.o
  LD  glide3x.dll
make[1]: Entering directory '/home/user/myqemu/qemu-3dfx/wrappers/3dfx/dxe'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/user/myqemu/qemu-3dfx/wrappers/3dfx/dxe'
make[1]: Entering directory '/home/user/myqemu/qemu-3dfx/wrappers/3dfx/ovl'
  WCC glideovl.obj
  CFLAGS  -zq -we -6s -ohtx -bd -fpi87
  WLD glide2x.ovl
Error! E2008: cannot open glideovl.obj : No such file or directory
make[1]: *** [Makefile:14: glide2x.ovl] Error 1
make[1]: Leaving directory '/home/user/myqemu/qemu-3dfx/wrappers/3dfx/ovl'
make: *** [Makefile:29: fxdrv] Error 2

**Comment by kjliew** [comment]
This is your Watcom C/C++ build environment issue, **irrelevant to the project**.
Just use DOSBox for DOS games. Otherwise, support the project by making a small donation and QEMU binary package including DOS/DJGPP OVL/DXE wrappers will be delivered for you. Details at https://github.com/kjliew/qemu-3dfx#donation
