### ISSUE TITLE
Please provide instructions to patch Virglrenderer On Windows Using Mingw

### ISSUE THREAD

**Issue by UmarAhmed129** [kjliew/qemu-3dfx#63]
I am specifically talking about 

https://github.com/kjliew/qemu-3dfx/blob/master/virgil3d/MINGW-packages/0001-Virglrenderer-on-Windows-and-macOS.patch

Also you use qemu 6.2.0. Will it work on the latest released version 7.0 of qemu?
Or 
Is there a different patch for qemu 7.0.

Thanks

**Comment by kjliew** [comment]
When you make a small donation to support the project, the QEMU binary package will include Virgil3D for the chosen host platform. Details at https://github.com/kjliew/qemu-3dfx#donation
