### ISSUE TITLE
Questions about running QEMU on Windows

### ISSUE THREAD

**Issue by anderspitman** [kjliew/qemu-3dfx#69]
Hey @kjliew, love your videos. You seem to be one of the few people doing much with QEMU on Windows hosts. Do you by chance have any experience getting faster networking up and running? I find the user mode networking through slirp to be rather slow.

**Comment by kjliew** [comment]
I don't have quantitative measure to gauge network performance. I think the best networking performance from QEMU on Windows host is with `virtio-net-pci` on tuntap (tap-windows) and WHPX APIC emulation. This setup currently works best for modern Linux VM on Windows host. Tuntap works best with wired connection but a lot slower with wireless. WHPX APIC emulation isn't quite functional yet for Windows VM. The `virtio-net-pci` requires at least WinXP guest but delivers better performance on Win7+ guest with Q35 machine model.

Unfortunately, there is not a lot of knobs for QEMU on Windows host.

**Comment by anderspitman** [comment]
Thanks for the response. This is very useful information. I managed to install tap-windows by downloading the latest OpenVPN from [here](https://openvpn.net/community-downloads/) and installing just the Tap-Windows component. Haven't tested with QEMU yet, but is that the way you install it? Have you played around with the newer drivers mentioned [here](https://www.reddit.com/r/OpenVPN/comments/vjo777/limitations_of_openvpn_ce/) by chance?

Fortunately I actually don't need Windows VM functionality. Just Linux.

Do you document the commands you use to start QEMU anywhere? I bet you've learned a lot of useful tweaks.

**Comment by kjliew** [comment]
Yes, the OpenVPN tap-windows is what I am using. I downloaded from [here](https://build.openvpn.net/downloads/releases/) instead for simplicity. You can check out the wiki page for the commands. I don't think there is anything interesting for the network tweaking. I don't have access to enterprise-grade infrastructure at 10Gb+ to be able to appreciate high-speed networking. The project is all about retro games use cases and either slirp or tuntap are doing just fine.

**Comment by anderspitman** [comment]
Again, thank you!
