### ISSUE TITLE
add chmod +x to sign_commit in the instructions

### ISSUE THREAD

**Issue by Askmewho** [kjliew/qemu-3dfx#7]
First, amazing project. Maybe I was too ambitious to get it working on ARM without kvm, but this project seems really cool for modern low power x86 hardware to make real retro desktop experience and also,retro pc gaming. I will make a youtube video tutorial when I get this working

salva@ROCK-Pi-X:~/myqemu/qemu-3dfx/qemu-5.2.0$ ../scripts/sign_commit
bash: ../scripts/sign_commit: Permission denied

add sudo chmod +x  ../scripts/sign_commit on the tutorial

also, it would be cool if you add the files required (those libs) to get the hw acceleration on the repo so we dont have to jump over the forums to get them :) 

mmm.. I didnt tried already the hw acceleration... the sound works terrible even with kvm.. I will try to recompile it with another drivers different from pulse... 
on another note, would be cool if you could include gallium9 (somehow) down the road, taking in count some drivers are moving to gallium, like the intel ones with Iris.

**Comment by kjliew** [comment]
The video you made on ARM seems to have problem with OpenGlide that might have slowed things down. Otherwise, my performance estimation on ARM should be able to play NFS2SE at 22~27FPS. NFS2SE is not a very demanding game. A 1.5~2.0  ARMv8 64-bit system should be able to manage it. I maintain a local version of OpenGlide that is optimized and bugs fixed for QEMU, especially for Linux x86. If you wish to give it another shot, then let me know.

I wish to get my hands on PineBook Pro, but it is currently out-of-stock.

**Comment by Askmewho** [comment]
well, I don't expect this to be usable at all on ARM anytime soon. for just playing games box86 is far superior, but this is just for retro feeling :)

**Comment by kjliew** [comment]
Which game in particular? You can try `alsa` audio driver instead of `pa` for Linux.

**Comment by Askmewho** [comment]
yeah, I tried alsa, didn't change that much on xp, on win98 was a bit better. this works on xp too? I didn't try any gane already. the sound works as bad to not even deserve it.

**Comment by kjliew** [comment]
I emulate AC97 on QEMU for Windows guests. Most Windows games I tried were OK, to name a few, Quake2, NFS3, Mechwarrior 2, MotoRacer, Half Life, Homeworld etc. They worked both on Windows 10 and Linux host. Some games audio were choppy during FMV, but in-game audio was OK.

I posted a video running Final Reality demo with sound. You can check if it sounded OK.
https://youtu.be/X7Fqg-JDGSo

QEMU 5.2.0 has improved audio compared to older versions from the 4.x.

**Comment by kjliew** [comment]
@Askmewho Hi I made available my OpenGlide fork optimized for QEMU.

I am very interested to know how it will help QEMU on 3Dfx games on RPi4/RockPi or similar AArch64 platforms compared to Box86 + Wine x86.

**Comment by Askmewho** [comment]
ohh no, box86 is way faster, there is no comparison. but, this project is cool bc of the retro feeling. sadly... I had too bad sound to even try it on x86. I will warn you if I test it again.
