### ISSUE TITLE
Support for API S3 Virge, PowerVR, ATI 3D Rage, Matrox Millenium, Matrox Mystique, NVIDIA NV1, Rendition Verite etc

### ISSUE THREAD

**Issue by MrPepka** [kjliew/qemu-3dfx#70]
There are games that use custom APIs written for specific graphics cards (MechWarrior 2 had OEM versions for S3 Virge, Matrox Mystique, PowerVR, ATI 3D Rage cards, there were a lot of games for PowerVR, such as Moon Racer and there were also games with special OEM versions using the aforementioned APIs) and the problem is that these games are difficult to run on modern equipment (games using the S3 Virge API can only be run on S3 Virge emulators, such as PCem or 86box, similarly with games using the Matrox API, and e.g. games using the PowerVR API or NVIDIA NV1 cannot be launched at all). Is support for these APIs foreseen (if possible)? There is some wrapper for ATI 3D Rage, for Matrox and S3 Virge there are no wrappers as well as for PowerVR or NVIDIA NV1

**Comment by kjliew** [comment]
When someone made the devotion to port those old-timers' 3D APIs into modern APIs, such as OpenGL, then QEMU would have already supported them. Examples are OpenGLide and ATI GLRage.

Frankly, S3 ViRGE and Matrox MSI are garbage 3D APIs for Games. The have no exclusive ports. All their game ports are available in the superior 3Dfx Glide or Direct3D. 

The S3 ViRGE API goes well with "**_the other camp_**" emulators, both are garbage in the context of Windows Games.🤣...🤣
