### ISSUE TITLE
Would a release in the AUR be possible?

### ISSUE THREAD

**Issue by SoftwareRat** [kjliew/qemu-3dfx#71]
Would make compiling the project easier, I might be able to help

**Comment by kjliew** [comment]
Anything is possible with GPL, just read the **LICENSE**. You just need someone to have the devotion to do it.

For those who believe in the course of Game Preservation, the best way to help is to make a small donation with Game Election.  There is nothing better than having those Games for one's nostalgia preserved in _**"Pristine Conditiion"**_ relieving the hassles to read through pages of PC Games Wiki, hunting for fans' mods/patches or hoping for a remake.
