### ISSUE TITLE
Superbike 2001

### ISSUE THREAD

**Issue by sJARB** [kjliew/qemu-3dfx#72]
From : https://youtu.be/8Oq2tJLe4vA

Hello, I'd like to know how do you get the game working like this !

Best regards, sJARB

**Comment by kjliew** [comment]
All the details are fully published in GitHub pages/wiki and the YouTube channel.

Supports for specific games are available through **Game Election** with a small donation to support the project and **Game Preservation** with elected games. More details at https://github.com/kjliew/qemu-3dfx#donation
