### ISSUE TITLE
Few questions about a program

### ISSUE THREAD

**Issue by MrPepka** [kjliew/qemu-3dfx#76]
I have a few questions:
1. In some videos I saw that some applications (such as 3DMark) or some games detect the graphics card as GeForce 6800, ATI Radeon HD 5600 Series etc etc. How does it work? Besides changing the graphics card IDs (Vendor ID and Device ID), do you emulate any driver features from them? Isn't it worth doing that?
2. Are you planning to set up a Discord server for your project?
Thank you in advance for your response

**Comment by kjliew** [comment]
Your mind is too clouded with the **\*BS\* from PCem** on everything about emulation and the fanboys' stupidity. Such as the following VOGONS post calling those games **"work"** on Banshee emulation and a full HD screenshot of MDK2.
https://www.vogons.org/viewtopic.php?p=915671#p915671
Go and play those games on PCem and you will get why I just LAUGHED ...🤣🤣Oh yeah, the fanboy was still right, they "work" just don't play them. When they were foolishly stuck over there, they can't see the light of the day.

1. Just read WineD3D source codes or check out the comments under the videos you watched.
2. Not at the moment. Aren't GitHub and YouTube good enough?
