### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Rosabis** [kjliew/qemu-3dfx#77]
QEMU will crash after showing "Starting up Windows 98" after enable haxm, only use tcg will work correctly, I don't know why,the host system is Windows 7.

**Comment by kjliew** [comment]
Your best hope is to check out if [Patcher9x](https://github.com/JHRobotics/patcher9x) will help.
Otherwise, report the issue there at https://github.com/intel/haxm

Windows 7 has long been EOL'ed. Time to move on, my friend!
