### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by User-3090** [kjliew/qemu-3dfx#79]
Pardon my ignorance, but I couldn't figure out a few things myself:

- Do I still need something that maps 3DFX calls to OpenGL like nGlide/OpenGlide/dgVoodoo installed?
- If not, are the wrappers in the project build from scratch or is it OpenGlide patched for QEMU?
- If not, is it still possible to use nGlide instead of the provided wrappers?
- Is the source code for additional donation features available or are these components closed source?

Thank you so much for all your time and dedication, your videos are amazing.

**Comment by kjliew** [comment]
>Do I still need something that maps 3DFX calls to OpenGL like nGlide/OpenGlide/dgVoodoo installed?
>If not, are the wrappers in the project build from scratch or is it OpenGlide patched for QEMU?

The Guest VM can pass-through 3Dfx Glide or OpenGL APIs. For 3Dfx Glide games, if you choose to pass-through Glide, then you will need to have something on the **Host** to receive that APIs. QEMU binary package bundles an optimized version of OpenGLide **Host-side** wrappers for such purposes. For the right versions, dgVoodoo2/nGlide/etc. can be the drop-in direct replacement. If you choose to pass-through OpenGL, then you will need something on the **Guest** to wrap Glide into OpenGL. QEMU binary package also bundles a version of OpenGLide as **Guest-side** wrappers for such purpuses.

Refer to https://github.com/kjliew/qemu-3dfx/wiki/QEMU-3D-APIs-Pass-Through for more details.

>If not, is it still possible to use nGlide instead of the provided wrappers?

Yes and No. There is no x86-64 Windows DLLs or native 64-bit ELF lib.so release for nGlide. I was provided x86-64 Windows DLLs dev-build from nGlide author without redistribution rights. You will have to check with nGlide author to get yours.

Opting for nGlide->(Wine)D3D9->OpenGL within Guest VM and pass-through OpenGL to Host is NOT recommended nor having 32-bit i686 build of QEMU to be able to use nGlide. _(whispering) "... 32-bit software must die ..."_

>Is the source code for additional donation features available or are these components closed source?

The instruction/source codes/details etc. to reproduce QEMU binary package are publicly available in accordance to each respective Open Source licenses. The donation is a courtesy in support for **Game Preservation** with build services. This is **\*NOT\* A SALE**.

If anyone disagrees, then the right thing to do is to report the violation to the copyright holders for further actions.

>Thank you so much for all your time and dedication, your videos are amazing.

You're welcome, and hope you enjoy them and have FUN with Good Old Games!
