### ISSUE TITLE
Any plans to submit official patch to QEMU for enabling Virgil 3D on Windows?

### ISSUE THREAD

**Issue by guanzhangrtk** [kjliew/qemu-3dfx#80]
Specifically I'm talking about this patch: https://github.com/kjliew/qemu-3dfx/blob/master/virgil3d/0001-Virgil3D-with-SDL2-OpenGL.patch

Looks like there was previous discussions on submitting a patch but it never happened: https://gitlab.freedesktop.org/virgl/virglrenderer/-/issues/217

Once accepted and merged with upstream, then you won't need to maintain your own patch for future releases.

Thanks a lot for your work!

**Comment by kjliew** [comment]
I welcome anyone with the time & patience to take the patch and upstream it. It's already GPL'ed after all. QEMU devs are free to take it if they like it.

**Comment by guanzhangrtk** [comment]
Sounds good. Thanks for taking the time to answer and please keep up the good work!

**Comment by dyharlan** [comment]
I really hope there's a 2nd attempt to upstream this to qemu. Quite a shame if it gets abandoned.
