### ISSUE TITLE
Building qemu error

### ISSUE THREAD

**Issue by MatviCoolk** [kjliew/qemu-3dfx#82]
After the command `../qemu-7.2.0/configure && make`:

# Log

[1823/6780] Compiling C object libcommon.fa.p/hw_display_virtio-gpu-virgl.c.o
FAILED: libcommon.fa.p/hw_display_virtio-gpu-virgl.c.o 
cc -Ilibcommon.fa.p -I../qemu-7.2.0/dtc/libfdt -I/opt/homebrew/Cellar/capstone/4.0.2/include/capstone -I/opt/homebrew/Cellar/pixman/0.40.0/include/pixman-1 -I/opt/homebrew/Cellar/libpng/1.6.38/include/libpng16 -I/opt/homebrew/Cellar/spice-protocol/0.14.4/include/spice-1 -I/opt/homebrew/Cellar/jpeg-turbo/2.1.4/include -I/opt/homebrew/Cellar/gnutls/3.7.8/include -I/opt/homebrew/Cellar/nettle/3.8.1/include -I/opt/homebrew/Cellar/libtasn1/4.19.0/include -I/opt/homebrew/Cellar/libidn2/2.3.4/include -I/opt/homebrew/Cellar/p11-kit/0.24.1_1/include/p11-kit-1 -I/opt/homebrew/Cellar/libepoxy-angle/20210315.1/include -I/opt/homebrew/include -I/opt/homebrew/include/SDL2 -I/opt/homebrew/Cellar/glib/2.74.0/include -I/opt/homebrew/Cellar/glib/2.74.0/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.74.0/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.40/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi -I/opt/homebrew/Cellar/glib/2.74.0/include/gio-unix-2.0 -I/opt/homebrew/Cellar/zstd/1.5.2/include -I/opt/homebrew/Cellar/libslirp/4.7.0/include/slirp -I/opt/homebrew/include/virgl -I/opt/homebrew/Cellar/libusb/1.0.26/include/libusb-1.0 -fcolor-diagnostics -Wall -Winvalid-pch -std=gnu11 -O2 -g -iquote . -iquote /Users/MatviCoolk/qemu-3dfx/qemu-7.2.0 -iquote /Users/MatviCoolk/qemu-3dfx/qemu-7.2.0/include -iquote /Users/MatviCoolk/qemu-3dfx/qemu-7.2.0/tcg/aarch64 -DOS_OBJECT_USE_OBJC=0 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wno-initializer-overrides -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-string-plus-int -Wno-typedef-redefinition -Wno-tautological-type-limit-compare -Wno-psabi -Wno-gnu-variable-sized-type-not-at-end -fstack-protector-strong -DNCURSES_WIDECHAR=1 -D_THREAD_SAFE -Wno-undef -DSTRUCT_IOVEC_DEFINED -MD -MQ libcommon.fa.p/hw_display_virtio-gpu-virgl.c.o -MF libcommon.fa.p/hw_display_virtio-gpu-virgl.c.o.d -o libcommon.fa.p/hw_display_virtio-gpu-virgl.c.o -c ../qemu-7.2.0/hw/display/virtio-gpu-virgl.c

../qemu-7.2.0/hw/display/virtio-gpu-virgl.c:147:41: error: variable has incomplete type 'struct virgl_renderer_resource_info'
    struct virgl_renderer_resource_info info;
                                        ^

../qemu-7.2.0/hw/display/virtio-gpu-virgl.c:147:12: note: forward declaration of 'struct virgl_renderer_resource_info'
    struct virgl_renderer_resource_info info;
           ^

../qemu-7.2.0/hw/display/virtio-gpu-virgl.c:165:15: error: implicit declaration of function 'virgl_renderer_resource_get_info' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = virgl_renderer_resource_get_info(ss.resource_id, &info);
              ^

2 errors generated.
ninja: build stopped: subcommand failed.
make: *** [run-ninja] Error 1

#

I don't know what to do.

**Comment by kjliew** [comment]
A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation. You're free to make inquiry on the supported platform of choice prior to making a donation.
