### ISSUE TITLE
Question about voodoo wrapper

### ISSUE THREAD

**Issue by michaeljhkim** [kjliew/qemu-3dfx#83]
So I've been checking out your custom glide api, and I think it looks great, but I am confused as to what the os' would see. If windows 98 se has this passthrough going on, what does it think is the gpu? 

Like, what gpu does windows see this as? Windows 98 se as the emulated os I mean.

**Comment by kjliew** [comment]
In API pass-through, the Guest OS does not have a need to see any GPU.
https://github.com/kjliew/qemu-3dfx/wiki/QEMU-3D-APIs-Pass-Through

**Comment by michaeljhkim** [comment]
What does it think it's using as a gpu then? 

I mean, a pc's gotta have one.

**Comment by kjliew** [comment]
I think it is easier to buy the games from GOG/Steam.
Grab a SteamDeck to play if you may, it is a FUN & NICE device.

**Comment by michaeljhkim** [comment]
> I think it is easier to buy the games from GOG/Steam. Grab a SteamDeck to play if you may, it is a FUN & NICE device.

Wait, I am not having an issue with installation, I am just wondering what windows 98 would be thinking is the GPU. 

Also, just telling people to take the easy way is NOT helping preservation. You should be incentivizing people to stay and check this out by making things easier on them. 
Imagine the positive attention this project could get by dosbox users, or 86box user, or just general retro PC enthusiasts by trying to make this whole thing friendlier to beginners. More people would bring more donations generally as well.

**Comment by kjliew** [comment]
"The world is a dark place."
"Who will protect the world from darkness?" -- Nocturne (1999)

There is something called preemptive judgement based on the nature of the question for the tendency in seeking for retro gaming solutions in VMs. You're free to ask the same question elsewhere.
