### ISSUE TITLE
Greedy Developer.

### ISSUE THREAD

**Issue by wilsontulus** [kjliew/qemu-3dfx#84]
Seemingly great lib at the outside, with all of these pics and videos, but unfortunately the dev is greedy enough that he even called obtaining those "exclusive" libraries donating, not buying. I mean, people will not even sure if he's even going to give the source code after we "donate" him? 

I mean sure, you want some rewards for your hard work, but why you even wanted to milk user's wallets just for some modified WineD3D libraries? $60 USD is still a lot of money for most of the users out there. Don't assume that everyone is willing enough to give you the USDs just for some modified WineD3D libraries that's made open source in the first place.

There's even a chance it could even be a scam, by any means, for example only the binaries (could even be OLLVM'ed!) are given and not the source code, thus further **violating WineD3D's LGPLv2 when you have to give back the modified libraries source code whenever it's even accessible by any means.** There's also a chance that the "perks" are fake or very delayed at the end.

By any means, massive L for this dev. Feels like we're dealing with another corporate tech clowns at this point.

**Comment by kjliew** [comment]
Feel free to report the violation for any action to be taken. Don't just be a GHOST!
