### ISSUE TITLE
Bug when building on Fedora and Ubuntu

### ISSUE THREAD

**Issue by Filechaser** [kjliew/qemu-3dfx#85]
Following the instructions on how to build qemu in the readme I get the following errors:
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_3dfx_glidept_mm.c.o: in function `processFRet':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidept_mm.c:631: undefined reference to `glide_renderer_stat'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_3dfx_glidept_mm.c.o: in function `processArgs':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidept_mm.c:558: undefined reference to `glide_renderer_stat'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_3dfx_glidewnd.c.o: in function `profile_stat':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidewnd.c:381: undefined reference to `glide_gui_fullscreen'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_3dfx_glidewnd.c.o: in function `stat_window':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidewnd.c:201: undefined reference to `glide_gui_fullscreen'
/usr/bin/ld: /home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidewnd.c:204: undefined reference to `glide_window_stat'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_3dfx_glidewnd.c.o: in function `fini_window':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidewnd.c:232: undefined reference to `glide_release_window'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_3dfx_glidewnd.c.o: in function `init_window':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidewnd.c:298: undefined reference to `glide_gui_fullscreen'
/usr/bin/ld: /home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/3dfx/glidewnd.c:335: undefined reference to `glide_prepare_window'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_linux.c.o: in function `MGLPresetPixelFormat':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_linux.c:496: undefined reference to `mesa_prepare_window'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_linux.c.o: in function `MesaDisplayModeset':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_linux.c:305: undefined reference to `mesa_gui_fullscreen'
/usr/bin/ld: /home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_linux.c:343: undefined reference to `mesa_gui_fullscreen'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_linux.c.o: in function `MGLWndRelease':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_linux.c:427: undefined reference to `mesa_release_window'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_linux.c.o: in function `MGLActivateHandler':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_linux.c:562: undefined reference to `mesa_renderer_stat'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `profile_stat':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:941: undefined reference to `mesa_gui_fullscreen'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `MGLMouseWarp':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:831: undefined reference to `mesa_mouse_warp'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `deactivateOnce':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:839: undefined reference to `mesa_renderer_stat'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `MGLCursorDefine':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:820: undefined reference to `mesa_cursor_define'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `MGLMouseWarp':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:831: undefined reference to `mesa_mouse_warp'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `deactivateOnce':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:839: undefined reference to `mesa_renderer_stat'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `MGLMouseWarp':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:831: undefined reference to `mesa_mouse_warp'
/usr/bin/ld: libqemu-i386-softmmu.fa.p/hw_mesa_mglcntx_mingw.c.o: in function `deactivateOnce':
/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build/../hw/mesa/mglcntx_mingw.c:839: undefined reference to `mesa_renderer_stat'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:165: run-ninja] Error 1
make[1]: Leaving directory '/home/parallels/myqemu/qemu-3dfx/qemu-7.2.0/build'
make: *** [GNUmakefile:11: all] Error 2

Could this please be fixed

**Comment by kjliew** [comment]
Fixed in https://github.com/kjliew/qemu-3dfx/commit/2a8d041df19a37f9ea7e4ba6c1e2b334f2b33e8e
