### ISSUE TITLE
Bug When Building in Windows MSYS2/Mingw64

### ISSUE THREAD

**Issue by Chuthamani018** [kjliew/qemu-3dfx#86]
[1645/1924] Compiling C++ object qga/vss-win32/qga-vss.dll.p/provider.cpp.obj
FAILED: qga/vss-win32/qga-vss.dll.p/provider.cpp.obj
"c++" "-m64" "-mcx16" "-Iqga/vss-win32/qga-vss.dll.p" "-Iqga/vss-win32" "-I../qemu-7.2.0/qga/vss-win32" "-I." "-Iqapi" "-Itrace" "-Iui" "-Iui/shader" "-IC:/msys64/mingw64/include/glib-2.0" "-IC:/msys64/mingw64/lib/glib-2.0/include" "-fdiagnostics-color=auto" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-std=gnu++11" "-O2" "-g" "-iquote" "." "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0" "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include" "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/tcg/i386" "-D__STDC_LIMIT_MACROS" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-U_FORTIFY_SOURCE" "-D_FORTIFY_SOURCE=2" "-fno-pie" "-no-pie" "-D_GNU_SOURCE" "-D_FILE_OFFSET_BITS=64" "-D_LARGEFILE_SOURCE" "-Wundef" "-Wwrite-strings" "-fno-strict-aliasing" "-fno-common" "-fwrapv" "-Wtype-limits" "-Wformat-security" "-Wformat-y2k" "-Winit-self" "-Wignored-qualifiers" "-Wempty-body" "-Wendif-labels" "-Wexpansion-to-defined" "-Wimplicit-fallthrough=2" "-Wno-missing-include-dirs" "-Wno-shift-negative-value" "-Wno-psabi" "-fstack-protector-strong" "-Wno-unknown-pragmas" "-Wno-delete-non-virtual-dtor" "-Wno-non-virtual-dtor" -MD -MQ qga/vss-win32/qga-vss.dll.p/provider.cpp.obj -MF "qga/vss-win32/qga-vss.dll.p/provider.cpp.obj.d" -o qga/vss-win32/qga-vss.dll.p/provider.cpp.obj "-c" ../qemu-7.2.0/qga/vss-win32/provider.cpp
In file included from C:/msys64/mingw64/lib/glib-2.0/include/glibconfig.h:9,
                 from C:/msys64/mingw64/include/glib-2.0/glib/gtypes.h:34,
                 from C:/msys64/mingw64/include/glib-2.0/glib/galloca.h:34,
                 from C:/msys64/mingw64/include/glib-2.0/glib.h:32,
                 from C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/glib-compat.h:32,
                 from C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:144,
                 from ../qemu-7.2.0/qga/vss-win32/provider.cpp:13:
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: error: standard attributes in middle of decl-specifiers
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: note: standard attributes must precede the decl-specifiers to apply to the declaration, or follow them to apply to the type
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: warning: attribute ignored [-Wattributes]
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: note: an attribute that appertains to a type-specifier is ignored
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
[1646/1924] Compiling C object libqemu-i386-softmmu.fa.p/accel_tcg_cputlb.c.obj
[1647/1924] Compiling C++ object qga/vss-win32/qga-vss.dll.p/requester.cpp.obj
FAILED: qga/vss-win32/qga-vss.dll.p/requester.cpp.obj
"c++" "-m64" "-mcx16" "-Iqga/vss-win32/qga-vss.dll.p" "-Iqga/vss-win32" "-I../qemu-7.2.0/qga/vss-win32" "-I." "-Iqapi" "-Itrace" "-Iui" "-Iui/shader" "-IC:/msys64/mingw64/include/glib-2.0" "-IC:/msys64/mingw64/lib/glib-2.0/include" "-fdiagnostics-color=auto" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-std=gnu++11" "-O2" "-g" "-iquote" "." "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0" "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include" "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/tcg/i386" "-D__STDC_LIMIT_MACROS" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-U_FORTIFY_SOURCE" "-D_FORTIFY_SOURCE=2" "-fno-pie" "-no-pie" "-D_GNU_SOURCE" "-D_FILE_OFFSET_BITS=64" "-D_LARGEFILE_SOURCE" "-Wundef" "-Wwrite-strings" "-fno-strict-aliasing" "-fno-common" "-fwrapv" "-Wtype-limits" "-Wformat-security" "-Wformat-y2k" "-Winit-self" "-Wignored-qualifiers" "-Wempty-body" "-Wendif-labels" "-Wexpansion-to-defined" "-Wimplicit-fallthrough=2" "-Wno-missing-include-dirs" "-Wno-shift-negative-value" "-Wno-psabi" "-fstack-protector-strong" "-Wno-unknown-pragmas" "-Wno-delete-non-virtual-dtor" "-Wno-non-virtual-dtor" -MD -MQ qga/vss-win32/qga-vss.dll.p/requester.cpp.obj -MF "qga/vss-win32/qga-vss.dll.p/requester.cpp.obj.d" -o qga/vss-win32/qga-vss.dll.p/requester.cpp.obj "-c" ../qemu-7.2.0/qga/vss-win32/requester.cpp
In file included from C:/msys64/mingw64/lib/glib-2.0/include/glibconfig.h:9,
                 from C:/msys64/mingw64/include/glib-2.0/glib/gtypes.h:34,
                 from C:/msys64/mingw64/include/glib-2.0/glib/galloca.h:34,
                 from C:/msys64/mingw64/include/glib-2.0/glib.h:32,
                 from C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/glib-compat.h:32,
                 from C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:144,
                 from ../qemu-7.2.0/qga/vss-win32/requester.cpp:13:
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: error: standard attributes in middle of decl-specifiers
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: note: standard attributes must precede the decl-specifiers to apply to the declaration, or follow them to apply to the type
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: warning: attribute ignored [-Wattributes]
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: note: an attribute that appertains to a type-specifier is ignored
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
[1648/1924] Compiling C object qga/qemu-ga.exe.p/meson-generated_.._qga-qapi-init-commands.c.obj
[1649/1924] Compiling C object qga/qemu-ga.exe.p/meson-generated_.._qga-qapi-introspect.c.obj
[1650/1924] Compiling C++ object qga/vss-win32/qga-vss.dll.p/install.cpp.obj
FAILED: qga/vss-win32/qga-vss.dll.p/install.cpp.obj
"c++" "-m64" "-mcx16" "-Iqga/vss-win32/qga-vss.dll.p" "-Iqga/vss-win32" "-I../qemu-7.2.0/qga/vss-win32" "-I." "-Iqapi" "-Itrace" "-Iui" "-Iui/shader" "-IC:/msys64/mingw64/include/glib-2.0" "-IC:/msys64/mingw64/lib/glib-2.0/include" "-fdiagnostics-color=auto" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-std=gnu++11" "-O2" "-g" "-iquote" "." "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0" "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include" "-iquote" "C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/tcg/i386" "-D__STDC_LIMIT_MACROS" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-U_FORTIFY_SOURCE" "-D_FORTIFY_SOURCE=2" "-fno-pie" "-no-pie" "-D_GNU_SOURCE" "-D_FILE_OFFSET_BITS=64" "-D_LARGEFILE_SOURCE" "-Wundef" "-Wwrite-strings" "-fno-strict-aliasing" "-fno-common" "-fwrapv" "-Wtype-limits" "-Wformat-security" "-Wformat-y2k" "-Winit-self" "-Wignored-qualifiers" "-Wempty-body" "-Wendif-labels" "-Wexpansion-to-defined" "-Wimplicit-fallthrough=2" "-Wno-missing-include-dirs" "-Wno-shift-negative-value" "-Wno-psabi" "-fstack-protector-strong" "-Wno-unknown-pragmas" "-Wno-delete-non-virtual-dtor" "-Wno-non-virtual-dtor" -MD -MQ qga/vss-win32/qga-vss.dll.p/install.cpp.obj -MF "qga/vss-win32/qga-vss.dll.p/install.cpp.obj.d" -o qga/vss-win32/qga-vss.dll.p/install.cpp.obj "-c" ../qemu-7.2.0/qga/vss-win32/install.cpp
In file included from C:/msys64/mingw64/lib/glib-2.0/include/glibconfig.h:9,
                 from C:/msys64/mingw64/include/glib-2.0/glib/gtypes.h:34,
                 from C:/msys64/mingw64/include/glib-2.0/glib/galloca.h:34,
                 from C:/msys64/mingw64/include/glib-2.0/glib.h:32,
                 from C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/glib-compat.h:32,
                 from C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:144,
                 from ../qemu-7.2.0/qga/vss-win32/install.cpp:13:
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: error: standard attributes in middle of decl-specifiers
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: note: standard attributes must precede the decl-specifiers to apply to the declaration, or follow them to apply to the type
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: warning: attribute ignored [-Wattributes]
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
C:/msys64/mingw64/include/glib-2.0/glib/gmacros.h:1076:21: note: an attribute that appertains to a type-specifier is ignored
 1076 | # define G_NORETURN [[noreturn]]
      |                     ^
C:/msys64/home/Administrator/myqemu/qemu-3dfx/qemu-7.2.0/include/qemu/osdep.h:180:8: note: in expansion of macro 'G_NORETURN'
  180 | extern G_NORETURN
      |        ^~~~~~~~~~
[1651/1924] Compiling C object qga/qemu-ga.exe.p/meson-generated_.._qga-qapi-types.c.obj
[1652/1924] Compiling C object libqemu-i386-softmmu.fa.p/fpu_softfloat.c.obj
ninja: build stopped: subcommand failed.
make: *** [Makefile:165: run-ninja] Error 1

Can you please fix it

**Comment by kjliew** [comment]
A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation. You're free to make inquiry on the supported platform of choice prior to making a donation.

**Comment by thePublicer** [comment]
change extern G_NORETURN to G_NORETURN extern
