### ISSUE TITLE
configure and make fails on MSYS2

### ISSUE THREAD

**Issue by aabluedragon** [kjliew/qemu-3dfx#88]
Attached command and output
```
../qemu-7.2.2/configure && make
Using './build' as the directory for build output
ERROR: Unrecognized host OS (uname -s reports 'MSYS_NT-10.0-22621')
```

**Comment by kjliew** [comment]
https://wiki.qemu.org/Hosts/W32

A small donation to support the project & Game Preservation will have the QEMU prebuilt binaries delivered for you for your platform of choice. See details at https://github.com/kjliew/qemu-3dfx#donation. You're free to make inquiry on the supported platform of choice prior to making a donation.
