### ISSUE TITLE
More specific version info (just a suggestion)

### ISSUE THREAD

**Issue by misutoneko** [kjliew/qemu-3dfx#9]
For scripting there will be a need to determine the specific git level that the qemu binary was built against (at run-time).
It would also help the users to ensure they're in fact running qemu-3dfx and not vanilla qemu (and also, to match their guest stubs).
A safe way to do this would be to add this information to the -V switch, it's just a printf().

**Comment by kjliew** [comment]
Fixed in https://github.com/kjliew/qemu-3dfx/commit/884093a5ffff4479b256800f46253874a10fba37. I made a typo in the commit message.
Sample output:
```
$ ./qemu-system-i386 --version
QEMU emulator version 5.2.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
  featuring qemu-3dfx@884093a-16:05:42 Mar 28 2021 build
```

**Comment by misutoneko** [comment]
Perfect. Thank you!
