### ISSUE TITLE
Win98/ME hangs when using accel=whpx (windows host)

### ISSUE THREAD

**Issue by aabluedragon** [kjliew/qemu-3dfx#91]
I followed your guide on installing Windows 98 SE (tried both Retail and OEM).
Also tried with and without applying patch9x.
Had to remove the argument `-cpu host` because it's invalid in windows host, and changed `accel=kvm` to `accel=whpx` for windows hyper visor.

Once Windows guest 98SE/ME boots up, it hangs completely, when using `whpx` (although installation finished fine with it).
without `whpx`, the system boots and works.

Tested on both QEMU8 and QEMU 7.2.2 (after applying your 3dfx patch).

Also tried both `qemu-system-i386` and `qemu-system-x86_64`, same behavior.

also seeing "Windows Protection Error" upon every 1 out of 2 boots or so, regardless of using `whpx` or not, with/without patch9x.

Tried with `accel=hax` (after installing intel haxm), but it said that argument is invalid.

**Comment by kjliew** [comment]
**QEMU general usability issues are out of scope of this project.**
