### ISSUE TITLE
hd img copy with donation

### ISSUE THREAD

**Issue by aabluedragon** [kjliew/qemu-3dfx#92]
Hi, 

If I donate, could I also have a copy of your preinstalled win98se hd img with all the updates/patches?

Thanks,
Alon

**Comment by kjliew** [comment]
When one made a donation to support the project and Game Preservation, the exercisable donor's privileges are clearly outlined at https://github.com/kjliew/qemu-3dfx#donation. The project respects and honors FOSS/propriety software licensing and distribution rights as required by laws.
