### ISSUE TITLE
The compilation of the wrappers are broken (No, I won't donate, I want to do this myself)

### ISSUE THREAD

**Issue by TerryTRSPanda** [kjliew/qemu-3dfx#97]
`make
  CC  fxhook.o fxhpat.o fxlib9x.o fxlibnt.o md5.o 
cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI
cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI
cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI
cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI
cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI
make: *** [Makefile:75: fxlib] Error 1
`
I edited the makefile and got rid of the x86-64-v2 crap and got this

`  CC  fxhook.o fxhpat.o fxlib9x.o fxlibnt.o md5.o 
../../fxlib/fxhook.c: In function ‘HookTimeGetTime’:
../../fxlib/fxhook.c:263:5: error: a label can only be part of a statement and a declaration is not a statement
  263 |     PCOMPATFX nptr = fxCompatTblPtr();
      |     ^~~~~~~~~
make: *** No rule to make target 'fxhook.o', needed by 'glide.dll'.  Stop.
`

Others have a suspicion that kjliew is greedy, but I'm acting in good faith that they're not just doing the bare minimum to comply with the GPL whilst obfuscating the compilation process and is just simply unaware that their build instructions aren't verbose enough and I would like to help them out and thus, helping out the community especially those like myself who are a fixed income pensioner and $60 is a lot of money for me and actually, I just checked my bank account, if I donated $60 right now, I would have a negative balance.

**Comment by thePublicer** [comment]
Secret: dHlwZSBodHRwczovL3Rpbnl1cmwoZG90KWNvbS8za213ZGNqOQ==

**Comment by thePublicer** [comment]
also he is not give the qemu-3dfx package if you donate.


> **Donor's priviledges in build service is temporary HALTED indefinitely. Donations remain welcomed and accepted but no build for platform of choice can be delivered nor fulfiling Game Election services for Game Preservation.**

**Comment by TerryTRSPanda** [comment]
I have no idea what you posted. Also, it's good that the policy changed, I haven't been here in a while.

**Comment by thePublicer** [comment]
it has the url in it you have to decode it

**Comment by thePublicer** [comment]
> Secret: dHlwZSBodHRwczovL3Rpbnl1cmwoZG90KWNvbS8za213ZGNqOQ==

it has the url in it you have to decode it

**Comment by thePublicer** [comment]
> Secret: dHlwZSBodHRwczovL3Rpbnl1cmwoZG90KWNvbS8za213ZGNqOQ==

https://www.base64decode.org/
decode quick before kjliew deletes this comments

**Comment by kjliew** [comment]
See https://github.com/kjliew/qemu-3dfx/pull/96

Thanks for being in good faith. The Donation used to serve other purposes. VOGONS purged all the qemu-3dfx threads where such purposes were explained upon the origin of the project. Shame on the Unprofessional Moderator @vogonsorg.

@thePublicer I decoded the secret. It does not have to be such secretive. I am no lawyer to go after anyone. After all, it is FOSS. Thank YOU for supporting the Project and Game Preservation.

**Comment by thePublicer** [comment]
https://tinyurl.com/3kmwdcj9

**Comment by casasfernando** [comment]
> `make CC fxhook.o fxhpat.o fxlib9x.o fxlibnt.o md5.o cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI cc1: error: ‘x86-64-v2’ architecture level is only defined for the x86-64 psABI make: *** [Makefile:75: fxlib] Error 1 ` I edited the makefile and got rid of the x86-64-v2 crap and got this
> 
> ` CC fxhook.o fxhpat.o fxlib9x.o fxlibnt.o md5.o ../../fxlib/fxhook.c: In function ‘HookTimeGetTime’: ../../fxlib/fxhook.c:263:5: error: a label can only be part of a statement and a declaration is not a statement 263 | PCOMPATFX nptr = fxCompatTblPtr(); | ^~~~~~~~~ make: *** No rule to make target 'fxhook.o', needed by 'glide.dll'. Stop.`
> 
> Others have a suspicion that kjliew is greedy, but I'm acting in good faith that they're not just doing the bare minimum to comply with the GPL whilst obfuscating the compilation process and is just simply unaware that their build instructions aren't verbose enough and I would like to help them out and thus, helping out the community especially those like myself who are a fixed income pensioner and $60 is a lot of money for me and actually, I just checked my bank account, if I donated $60 right now, I would have a negative balance.

@TerryTRSPanda first error about "‘x86-64-v2’ architecture level" is probably cause by using gcc version < 11. Try to build the code using a newer version of gcc. gcc 11 is present in both, Ubuntu 22.04 and Debian 12.

Second problem about "a label can only be part of a statement" should be fixed by a simple patch to the source code:
```
sed -i -e 's|compat_patched:|compat_patched: ; // Solves build error: a label can only be part of a statement and a declaration is not a statement|g' qemu-3dfx/wrappers/fxlib/fxhook.c
```

Hope it helps.

**Comment by thePublicer** [comment]
do a search on this repository issues or use google.
